### ISSUE TITLE
Show description at the top of the meta box

### ISSUE THREAD

**Issue by danielbachhuber** [alleyinteractive/wordpress-fieldmanager#102]
As a way of introducing the fields in the meta box to the user, I'd like to have the description appear at the top of the meta box, instead of the bottom where it currently is now:

![image](https://f.cloud.github.com/assets/36432/2375412/38e376f6-a86b-11e3-8561-4fc2b2a2b745.png)

Alternatively, we could come up with another paradigm for "help text" that would be positioned separately.

**Comment by danielbachhuber** [comment]
@mboynes Opinions on this? It's come up again.

**Comment by montchr** [comment]
I'd really like this to happen too. +1
