### ISSUE TITLE
Post meta getter helper

### ISSUE THREAD

**Issue by danielbachhuber** [alleyinteractive/wordpress-fieldmanager#114]
I've written a helper for a base class like this:

```
/**
 * Get a given Fieldmanager field
 */
private function get_fm_field() {

	$vars = func_get_args();

	$pm_key = array_shift( $vars );

	$value = get_post_meta( $this->get_id(), $pm_key, true );

	foreach( $vars as $key ) {
		if ( isset( $value[ $key ] ) ) {
			$value = $value[ $key ];
		} else if ( empty( $value[ $key ] ) ) {
			return '';
		} 
	}

	return $value;

}
```

Usage: `$this->get_fm_field( 'project-details', 'background', 'background' )`

Would something like this be useful packaged with the plugin?

**Comment by mboynes** [comment]
Now that we've merged #255, I'm going to close this out. I think this was more necessary when presentation and data storage were entangled, but now that they aren't, I think this becomes less of a "must have". Of course, there's nothing stopping someone from dropping that snippet in their theme and using it (and I think that situation is preferable).
