### ISSUE TITLE
"0" (a string) is misconstrued as an empty value in textfields

### ISSUE THREAD

**Issue by xmattus** [alleyinteractive/wordpress-fieldmanager#132]

**Comment by zenkalia** [comment]
bump

**Comment by epylinkn** [comment]
:+1:

**Comment by xmattus** [comment]
I haven't looked into this at length since I filed the bug a while ago, but I would suspect the solution is to hunt down some place where a `!=` needs to become a `!==` or similar. We're certainly open to PRs if someone already has a fix.

**Comment by bcampeau** [comment]
I literally just ran into this last night. We need to fix it, although I haven't been able to hunt it down yet.

**Comment by xmattus** [comment]
I note that this only happens to text fields inside groups, so it's clearly related to serialization.

**Comment by xmattus** [comment]
See #444 for a fix.
