### ISSUE TITLE
allow 'slug' and 'post_name' storage option in datasource

### ISSUE THREAD

**Issue by netaustin** [alleyinteractive/wordpress-fieldmanager#16]
Will make migration to WordPress.com much easier.

**Comment by mboynes** [comment]
I was thinking we wouldn't do this, but I'm changing my mind. This is already done for the user datasource, so that should be used as a model for the others.

**Comment by mboynes** [comment]
We decided to kill this. If someone needs this functionality, the best approach would be to create a custom datasource class which extends an existing one, and change the relevant bits. This should be pretty easy to do overall.
