### ISSUE TITLE
Register fields for specific post types

### ISSUE THREAD

**Issue by danielbachhuber** [alleyinteractive/wordpress-fieldmanager#217]
Fieldmanager supports creating groups of fields, and "assigning" the group to a post type through `add_meta_box`.

If I have fields A,B,C, I should also be able to indicate that A,B can be present for all post types, but C should only be present for specific post types.

This way, I have consistent UI across all of my post types but can selectively show / hide post type-specific fields.

**Comment by dlh01** [comment]
@danielbachhuber,

Does the context infrastructure provide the flexibility you had in mind? For example:

```php
<?php
add_action( 'fm_post', function () {
	$context = fm_get_context();

	$children = [
		'foo' => new \Fieldmanager_TextField( 'Foo' ),
	];

	if ( 'page' === $context[1] ) {
		$children['bar'] = new \Fieldmanager_TextArea( 'Bar' );
	}

	$fm = new \Fieldmanager_Group( [
		'name' => 'baz',
		'children' => $children,
	] );
	$fm->add_meta_box( 'Baz', $context[1] );
} );
```

**Comment by danielbachhuber** [comment]
> Does the context infrastructure provide the flexibility you had in mind?

I have no memory of what I was trying to do in the original report :(
