### ISSUE TITLE
default_value doesn't work if save_to_post_parent is true

### ISSUE THREAD

**Issue by netaustin** [alleyinteractive/wordpress-fieldmanager#265]

**Comment by mboynes** [comment]
I was (mostly) unable to replicate this.

Using the following source, where I have a post with ID 1171...

```php
add_action( 'fm_post_post', function() {
	$fm = new Fieldmanager_Autocomplete( array(
		'name'           => 'debug_datasource_1',
		'default_value'  => 1171,
		'datasource'     => new Fieldmanager_Datasource_Post( array(
			'only_save_to_post_parent' => true,
			'query_args' => array( 'post_type' => 'post' ),
		) ),
	) );
	$fm->add_meta_box( 'Post Datasource 1', 'post' );
} );
```

... the correct post is in the autocomplete box.

However, if I change it to a `Fieldmanager_Select` field, and don't explicitly set `posts_per_page`, if my post is not listed in the first _n_ posts (where _n_ is the `posts_per_page` option), then the post won't be selected. That's a situation I don't think we should attempt to address. If this was **not** the original issue reported, that appears to be fixed.

Worth noting, I also tested with the field in a group.
