### ISSUE TITLE
Adhere to WP Coding Standards

### ISSUE THREAD

**Issue by mboynes** [alleyinteractive/wordpress-fieldmanager#271]
We are aiming to enforce the [WordPress coding standards](http://codex.wordpress.org/WordPress_Coding_Standards) across the entire plugin.

We'd love some help doing this spring cleaning. Below is a list of files that need to be verified or updated. If you want to chip in, comment on this issue saying that you're going to take one, and we'll update the issue to say you're on it. Then simply submit a PR with the clean file when you're done.
## PHP
- [x] `fieldmanager.php`
- [x] `php/class-fieldmanager-autocomplete.php`
- [x] `php/class-fieldmanager-checkbox.php`
- [x] `php/class-fieldmanager-checkboxes.php`
- [x] `php/class-fieldmanager-colorpicker.php`
- [x] `php/class-fieldmanager-datepicker.php`
- [x] `php/class-fieldmanager-draggablepost.php`
- [x] `php/class-fieldmanager-field.php`
- [x] `php/class-fieldmanager-grid.php`
- [x] `php/class-fieldmanager-group.php`
- [x] `php/class-fieldmanager-hidden.php`
- [x] `php/class-fieldmanager-link.php`
- [x] `php/class-fieldmanager-media.php`
- [x] `php/class-fieldmanager-options.php`
- [x] `php/class-fieldmanager-password.php`
- [x] `php/class-fieldmanager-radios.php`
- [x] `php/class-fieldmanager-richtextarea.php`
- [x] `php/class-fieldmanager-select.php`
- [x] `php/class-fieldmanager-textarea.php`
- [x] `php/class-fieldmanager-textfield.php`
- [x] `php/context/class-fieldmanager-context-page.php`
- [x] `php/context/class-fieldmanager-context-post.php`
- [x] `php/context/class-fieldmanager-context-quickedit.php`
- [x] `php/context/class-fieldmanager-context-storable.php`
- [x] `php/context/class-fieldmanager-context-submenu.php`
- [x] `php/context/class-fieldmanager-context-term.php`
- [x] `php/context/class-fieldmanager-context-user.php`
- [x] `php/context/class-fieldmanager-context.php`
- [x] `php/datasource/class-fieldmanager-datasource-post.php`
- [x] `php/datasource/class-fieldmanager-datasource-term.php`
- [x] `php/datasource/class-fieldmanager-datasource-user.php`
- [x] `php/datasource/class-fieldmanager-datasource.php`
- [x] `php/util/class-fieldmanager-util-term-meta.php`
- [x] `php/util/class-fieldmanager-util-validation.php`
- [x] `templates/datepicker.php`
- [x] `templates/options-checkboxes.php`
- [x] `templates/options-radios.php`
- [x] `templates/textfield.php`
## JS
- [ ] `js/fieldmanager-autocomplete.js`
- [ ] `js/fieldmanager-colorpicker.js`
- [ ] `js/fieldmanager-datepicker.js`
- [ ] `js/fieldmanager-draggablepost.js`
- [ ] `js/fieldmanager-group-tabs.js`
- [ ] `js/fieldmanager-post.js`
- [ ] `js/fieldmanager-quickedit.js`
- [ ] `js/fieldmanager-select.js`
- [ ] `js/fieldmanager.js`
- [ ] `js/grid.js`
- [ ] `js/media/fieldmanager-media.js`
- [ ] `js/richtext.js`
- [ ] `js/validation/fieldmanager-validation.js`

**Comment by danielbachhuber** [comment]
We're set up to do cleanup now, but because of the code churn required, we should do it as the very last thing.

**Comment by montchr** [comment]
If you still need help with this still, I'm willing to take a few files.

**Comment by danielbachhuber** [comment]
> If you still need help with this still, I'm willing to take a few files.

Great! I think now's a good time for it, given we're at the beginning of the next cycle and don't have too many outstanding pull requests.

Can you submit pull requests file by file, and enable PHPCS validation by Travis on the file at the beginning of the cleanup process? This will let us capture a failing build with all of the validations, and work towards a passing build.

**Comment by kjbenk** [comment]
I will pick up `fieldmanager.php`

**Comment by szepeviktor** [comment]
phpcbf can do miracles in 10 seconds.

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-autocomplete.php`

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-checkbox.php`

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-checkboxes.php`

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-colorpicker.php`

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-draggablepost.php`

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-field.php`

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-grid.php`

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-group.php`

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-hidden.php`

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-link.php`

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-media.php`

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-options.php`

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-radios.php`

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-richtextarea.php`

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-select.php`

**Comment by kjbenk** [comment]
On `php/context/class-fieldmanager-context-page.php`

**Comment by kjbenk** [comment]
On `php/class-fieldmanager-textfield.php`

**Comment by kjbenk** [comment]
On `php/context/class-fieldmanager-context-post.php`

**Comment by kjbenk** [comment]
On `php/context/class-fieldmanager-context-quickedit.php`

**Comment by kjbenk** [comment]
On `php/context/class-fieldmanager-context-storable.php`

**Comment by kjbenk** [comment]
On `php/context/class-fieldmanager-context-submenu.php`

**Comment by kjbenk** [comment]
On `php/context/class-fieldmanager-context-term.php`

**Comment by kjbenk** [comment]
On `php/context/class-fieldmanager-context-user.php`

**Comment by kjbenk** [comment]
On `php/context/class-fieldmanager-context.php`

**Comment by kjbenk** [comment]
On `php/datasource/class-fieldmanager-datasource-post.php`

**Comment by kjbenk** [comment]
On `php/datasource/class-fieldmanager-datasource-term.php`

**Comment by kjbenk** [comment]
On `php/datasource/class-fieldmanager-datasource-user.php`

**Comment by kjbenk** [comment]
On `php/datasource/class-fieldmanager-datasource.php`

**Comment by kjbenk** [comment]
On `php/util/class-fieldmanager-util-term-meta.php`

**Comment by kjbenk** [comment]
On `php/util/class-fieldmanager-util-validation.php`

**Comment by kjbenk** [comment]
On `templates/options-radios.php`

**Comment by kjbenk** [comment]
On `templates/textfield.php`

**Comment by mboynes** [comment]
I don't think it's worthwhile to update the JS at this time. The JS for this plugin needs a complete overhaul, moving it to webpack, etc., so I'm going to mark this as resolved now that the PHP files are all done.
