### ISSUE TITLE
"Add More" at top leaves empty element in the bottom

### ISSUE THREAD

**Issue by danielbachhuber** [alleyinteractive/wordpress-fieldmanager#277]
See screenshot:

![image](https://cloud.githubusercontent.com/assets/36432/5530425/5e9eca76-89d4-11e4-936e-b9568eadfec0.png)

When "Add More" position is top, I'd expect this empty element to be right below the button.

cc @jitendraharpalani58

**Comment by nschoenholtz** [comment]
I recently added this to fieldmanager-demos [here](https://github.com/alleyinteractive/fieldmanager-demos/blob/master/lib/class-fm-demo-text.php#L54) and didn't see this behavior -- I also tried setting `one_label_per_item => false` to more closely mimic the screenshot and it still didn't occur. @danielbachhuber is this bug still happening for you?

**Comment by danielbachhuber** [comment]
Nope, I can't reproduce now either. We can close.
