### ISSUE TITLE
Post context only checks permissions if post type is "post"

### ISSUE THREAD

**Issue by mboynes** [alleyinteractive/wordpress-fieldmanager#281]
See [class-fieldmanager-context-post.php](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/dbbd65fc608794720a330050657c8b8ff08a7c83/php/context/class-fieldmanager-context-post.php#L198-L204). This should apply to all post types. When fixing this, unit testing should test that another post type works as expected, even when using custom capabilities.

**Comment by danielbachhuber** [comment]
This was fixed as a part of #173
