### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Sitetools** [alleyinteractive/wordpress-fieldmanager#303]
When I install a fresh download of fieldmanager on WP 4.1 (latest) I get this Fatal error:

Parse error: syntax error, unexpected T_FUNCTION in ..../subdomains/lovebite/httpdocs/wp-content/plugins/wordpress-fieldmanager-master/fieldmanager.php on line 175

Any idea what could be causing this?

**Comment by danielbachhuber** [comment]
You're running PHP 5.2 and Fieldmanager requires PHP 5.3+

**Comment by Sitetools** [comment]
Perfect, thanks for that. 
I'll push the client for better hosting.
