### ISSUE TITLE
Order Children in admin

### ISSUE THREAD

**Issue by netm** [alleyinteractive/wordpress-fieldmanager#305]
Is it possible to add ordering (drag and drop ideally) to children of a group?

**Comment by dan-ai** [comment]
@netm i believe this is what you are looking for, https://github.com/alleyinteractive/fieldmanager-demos/blob/master/lib/class-fm-demo-text.php#L37-L39

**Comment by netm** [comment]
Ah,ha - Perfect! This plugin is fully awesome.
