### ISSUE TITLE
Color picker field

### ISSUE THREAD

**Issue by SteveS123** [alleyinteractive/wordpress-fieldmanager#312]
Does Fieldmanager supports building custom fields?  I see there isn't a color picker field available that would be handy.

**Comment by nschoenholtz** [comment]
You can absolutely write a subclass of a Fieldmanager field class and add custom handling. For a simple example, check out the way [Fieldmanager_Link](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/class-fieldmanager-link.php) extends Fieldmanager_TextField, changing the sanitization function.

You can write, say, `MyTheme_Fieldmanager_ColorPickerField` and include the file in your theme (eg, `require_once( MYTHEME_DIR . '/inc/class-mytheme-fieldmanager-colorpickerfield.php' )`).

**Comment by mboynes** [comment]
Resolved in #412
