### ISSUE TITLE
Add multiple groups to submenu context

### ISSUE THREAD

**Issue by jjeaton** [alleyinteractive/wordpress-fieldmanager#313]
I may just be missing something but it doesn't appear to be possible to add multiple groups in the Submenu Context.

The use case is having one options page that handles multiple settings on it, including some with repeatable fields. Even if it all gets saved to one options key, .et's say I have two text fields, and then I want to have a datasource field in a repeater so I can select multiple posts in an array for one of the keys. I can't seem to be able to do that in the current state.

**Comment by mboynes** [comment]
Hey @jjeaton, you can certainly add multiple groups to a Submenu context. Groups can be nested (indefinitely), and that's how to achieve what you need here. Create a single group, with multiple groups as its children. Everything will save to one option, which is the name of the top-most group.

Hope this helps!

**Comment by jjeaton** [comment]
If only I had just tried it. :) thanks!
