### ISSUE TITLE
Fieldmanager Group defaults

### ISSUE THREAD

**Issue by davisshaver** [alleyinteractive/wordpress-fieldmanager#316]
I would like to set a default for Fieldmanager Group, but the class doesn't support this - https://github.com/alleyinteractive/wordpress-fieldmanager/blob/af0e945b734d5fdac6085c9a740b60b224712d9d/php/class-fieldmanager-group.php

Would it make sense to add this? Ideas on implementation?

**Comment by mboynes** [comment]
You have (at least) two options here. First, create a group object with your defaults and clone it for each of your implementations. Second, create a class in your theme or plugin that extends Fieldmanager_Group which sets your defaults, and instantiate that instead. OOP FTW!
