### ISSUE TITLE
Group hidden by display_if gets saved accidentally

### ISSUE THREAD

**Issue by danielbachhuber** [alleyinteractive/wordpress-fieldmanager#325]
We have a modular Show editor backend powered by Fieldmanager:

![image](https://cloud.githubusercontent.com/assets/36432/7028699/617a985c-dd0c-11e4-9393-ce271f24362e.png)

The "Select" dropdown let's you pick from an available module, and fill out the details for the module if it's picked.

Here's the data that gets saved:

https://gist.github.com/danielbachhuber/bbc47b0fed27de1a48f7

As you can see, it appears our "prototype" is being saved each time. If a group is present via `display_if`, I'd expect it only get saved if the `display_if` value is present.

**Comment by danielbachhuber** [comment]
Another related bug https://github.com/alleyinteractive/wordpress-fieldmanager/commit/b0720299026e13bfdfd9e7dfec424bd270c1441a#diff-ae082fcb76024c82133d82bdef5c1930R636 causes empty group values to be persisted.

**Comment by mboynes** [comment]
Closing this as "won't fix". This would cause data loss and that wouldn't be obvious enough of an experience.

Alternative suggest: use FM's hooks to strip out the data on save and/or use JS to empty all hidden fields.
