### ISSUE TITLE
Add fields to existing metaboxes

### ISSUE THREAD

**Issue by johnciacia** [alleyinteractive/wordpress-fieldmanager#334]
It would be nice to be able to add additional fields to an existing metabox. 

I realize the `Fieldmanager_Group` allows you to add multiple fields to a single metabox. However, if there is an existing field that was created and does not use a `Fieldmanager_Group` it doesn't seem like there is a way to add another field.

Perhaps something like the following?
```
	$fm = new Fieldmanager_RichTextArea( false, array(
		'name' => 'field_1',
	) );
	$context = $fm->add_meta_box( 'Field', $post_types, $context, $priority );

	$fm = new Fieldmanager_RichTextArea( false, array(
		'name' => 'field_2',
	) );
	$context->add_field( $fm );
```

**Comment by mboynes** [comment]
There is a way to accomplish what you want.

Assuming you have this field,

```php
$fm = new Fieldmanager_RichTextArea( false, array(
    'name' => 'field_1',
) );
 $context = $fm->add_meta_box( 'Field', $post_types, $context, $priority );
```

... which already has data associated with it, and you want to add another field to the same meta box without affecting that data, you can use [serialize_data](https://github.com/alleyinteractive/wordpress-fieldmanager/wiki/Storing-data-unserialized) to put both fields in the same group but have them manage their data storage independently. Here's an example of adding both fields to the same meta box but each keeping their own meta keys:

```php
$fm = new Fieldmanager_Group( array(
    'name' => 'field_wrapper', // name this anything unique, it doesn't matter otherwise because we're disabling `add_to_prefix`
    'serialize_data' => false, // this tells FM to store each field separately instead of serializing them
    'add_to_prefix' => false, // this tells FM to not prefix the fields with `field_wrapper_`
    'children' => array(
        'field_1' => new Fieldmanager_RichTextArea,
        'field_2' => new Fieldmanager_RichTextArea,
    ),
) );
$fm->add_meta_box( 'Field', $post_types, $context, $priority );
```
