### ISSUE TITLE
jquery-ui-autocomplete enqueue

### ISSUE THREAD

**Issue by johnciacia** [alleyinteractive/wordpress-fieldmanager#335]
Is there any need to have jquery-ui-autocomplete enqueued on the front end?

https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/class-fieldmanager-autocomplete.php#L61

**Comment by danielbachhuber** [comment]
I suspect it's for frontend support for the fields.

However, the script likely should only be enqueued if the form is actually rendered. As it reads now, the script will always be enqueued when the class is instantiated

**Comment by mboynes** [comment]
> I suspect it's for frontend support for the fields.

Correct.

> However, the script likely should only be enqueued if the form is actually rendered.

Yes, this is the idea behind the context-specific actions, like `fm_post_{post_type}`, to ensure that classes are only instantiated (and scripts like this will only be enqueued) when they're relevant. Admittedly, the documentation is completely lacking on those actions, which I'm in the process of fixing. Here's the short version:

* posts: fm_post_{post type}
* users: fm_user
* quickedit: fm_quickedit_{post type}
* terms: fm_term_{taxonomy}
* submenus:   fm_submenu_{page} [specifically: `sanitize_text_field( $_GET['page'] )`]

    Submenus need to be registered first using `fm_register_submenu_page()`. Here's a full example:
    ```php
	if ( function_exists( 'fm_register_submenu_page' ) ) {
		fm_register_submenu_page( 'my_fields', 'tools.php', __( 'My Fields', 'locale' ) );
	}
	add_action( 'fm_submenu_my_fields', function() {
		$fm = new Fieldmanager_Textfield( __( 'Text Field', 'locale' ), array( 'name' => 'my_fields' ) );
		$fm->activate_submenu_page();
	} );
    ```
