### ISSUE TITLE
what is the current status of fieldmanager?

### ISSUE THREAD

**Issue by montchr** [alleyinteractive/wordpress-fieldmanager#351]
I'm a big fan of Fieldmanager, but there are some bugs that make it unusable for my team in its current state ( #296 specifically ). We've been using a fork ever since I opened #297 back in January, hoping that it would be merged soon, but the pull request remains open.

Due to the growing number of issues and open pull requests, I have to ask: what is the current state of the project and can we expect to see some of these PRs merged and issues resolved? And if yes, what might the timeframe look like?

**Comment by mboynes** [comment]
Hey @montchr, thanks for using the plugin, for reaching out, and for calling us out on this. You're absolutely right that we've been a bit slow to address this issue (and others) thus far in 2015. That's almost entirely my fault, and I'm very sorry about that.

The project is very much in active development, and it's currently getting a lot of attention. I recently kicked off a major docs initiative, and next on my list is to attack the PR and issue list. For the PR and issue you asked about specifically, I will get to them this week. Other PRs will be getting merged over the course of the next month or so depending on the feature, and issues will be attacked in order of severity (bugs before features).

If you have any more questions or run into any other problems, let me know!

**Comment by montchr** [comment]
Awesome, thanks @mboynes! :grinning: Very good news.

I did notice the documentation improvements, and it's been pretty helpful.

Thanks in advance for taking a look at my PR so promptly. Once things start picking up a bit I'd be happy to contribute some more PRs and some documentation stuff if you need that too.

**Comment by montchr** [comment]
Once again I'm curious about this. Where does the project currently stand? There are 34 open pull requests, including a few that have been around for over two years.

**Comment by mboynes** [comment]
Hey @montchr, Fieldmanager is absolutely under active development. If there are any features you feel are lacking or any old PRs that you're itching to see merged, please let us know! The main thing we're working on right now is UI enhancements.

Generally, we let interest drive feature development on this project. It's in a solid, stable place, and I'm not one to fix things that aren't broken or to add bloat to simple software. In cases of some older PRs, the lack of interest says something about how we might consider including those features. Perhaps they'll branch off into add-on plugins, or if there's ever a surge of interest we may decide to merge them.

Also of note, when possible, we try use core's idea of feature plugins. Some that we've been working on are [FM Zones](https://github.com/alleyinteractive/fm-zones), [FM Revisions](https://github.com/alleyinteractive/fieldmanager-revisions-alpha), [FM Widgets](https://github.com/alleyinteractive/fm-widgets), and [FM Datasource RSS](https://github.com/alleyinteractive/fm-datasource-rss). Some of these may find their way into Fieldmanager (revisions and widgets are both very likely, for example), and others may remain add-on plugins.

Feedback is always helpful for us, so if you see any PRs you're excited to use, or any open issues that would greatly improve Fieldmanager for you, please comment on them and let us know!
