### ISSUE TITLE
Fieldmanager data doesn't get save if `wp_update_term()` times out on cache purge

### ISSUE THREAD

**Issue by danielbachhuber** [alleyinteractive/wordpress-fieldmanager#354]
We're using Fieldmanager to create some metadata fields on our sections. However, when saving the term times out, our metadata doesn't get saved.

I suspect the timeout is happening on this process:

https://core.trac.wordpress.org/browser/trunk/src/wp-includes/taxonomy.php#L3596

Fieldmanager hooks in later:

https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/context/class-fieldmanager-context-term.php#L91

Have you run into this before? Any workarounds?

**Comment by nschoenholtz** [comment]
Yes, it's definitely the cache clearing process. We wrote a new context that can break out the meta fields into a separate settings page and therefore save them without having to run the term update -- @mboynes, do you know if we have permission to open source that?

**Comment by nschoenholtz** [comment]
(Wow, assignee menu freakout, sorry...) We have permission, I should have a PR up for this sometime today!

**Comment by mboynes** [comment]
@danielbachhuber: here's something to get you started:
https://gist.github.com/mboynes/bf7811a2958bb67cdde8

You can use it like so:

```php
function fieldmanager_term_page_demo() {
	$fm = new Fieldmanager_Group( array(
		'name' => 'term_page_demo',
		'children' => array(
			'some_setting' => new Fieldmanager_Select( array(
				'label' => __( 'Some Setting', 'fieldmanager' ),
				'options' => array(
					'one' => __( 'One', 'fieldmanager' ),
					'two' => __( 'Two', 'fieldmanager' ),
					'three' => __( 'Three', 'fieldmanager' ),
				),
			) ),
		),
	) );
	if ( class_exists( 'Fieldmanager_Context_Termpage' ) ) {
		$subpage = new Fieldmanager_Context_Termpage( __( 'Term Page Demo', 'fieldmanager' ), 'category', '', $fm );
	} else {
		$fm->add_term_form( __( 'Term Page Fallback', 'fieldmanager' ), 'category' );
	}
}
add_action( 'fm_term_category', 'fieldmanager_term_page_demo' );
if ( class_exists( 'Fieldmanager_Context_Termpage' ) ) {
	Fieldmanager_Context_Termpage::register_admin_bar_link( __( 'Term Page Demo', 'fieldmanager' ), 'category', 'term_page_demo' );
}
```

I looked through core's code to see if we should change where FM hooks, and unfortunately this is the best place. Any sooner in the chain and FM may get stale data from the cache.

**Comment by danielbachhuber** [comment]
Don't worry about rushing this. I'm working with VIP to get their async cache purging to a lower value, which solves the immediate problem for us.

**Comment by danielbachhuber** [comment]
#wontfix for this. We can't hook into an earlier action because we need the cache cleared, and slow cache purges are a problem of the object cache drop-ins.
