### ISSUE TITLE
Setting $skip_save = true on a field using $only_save_to_taxonomy still saves terms

### ISSUE THREAD

**Issue by mboynes** [alleyinteractive/wordpress-fieldmanager#362]
Setting `$skip_save` to `true` on a field using `$only_save_to_taxonomy` still saves terms. It _does not_ save post meta (related: #361).

Here's example code to replicate this:

```
function my_fm_only_save_category() {
	$fm = new Fieldmanager_Select( array(
		'name' => 'only-save-category',
		'remove_default_meta_boxes' => true,
		'skip_save' => true,
		'datasource' => new Fieldmanager_Datasource_Term( array(
			'taxonomy' => 'category',
			'only_save_to_taxonomy' => true,
		) ),
	) );
	$fm->add_meta_box( __( 'Test Group skip_save', 'fm-test' ), array( 'post' ) );
}
add_action( 'fm_post_post', 'my_fm_only_save_category' );
```

**Comment by danielbachhuber** [comment]
I'd consider this a bug, particularly because `$skip_save` is used for specific internal behavior too. If `$skip_save` is set, then my terms shouldn't be saved.

**Comment by mboynes** [comment]
@danielbachhuber: Noted, thanks for the input!

**Comment by mboynes** [comment]
I'm closing this as "won't fix".

`$skip_save` is an indicator to not save to the context, which is not the problem here. Truthfully, the real problem is that `$skip_save` is poorly named.
