### ISSUE TITLE
Doesn't work with WPML Translations

### ISSUE THREAD

**Issue by TwisterMc** [alleyinteractive/wordpress-fieldmanager#382]
Since Fieldmanager serializes the data, it doesn't work with WPML.
https://wpml.org/documentation/support/translating-custom-data-structures/

In order to make it work, we must first unserialize the data. Is there any way to do that?

We're in-between a rock and a hard place as we can't get our custom field content translated.

**Comment by wethecode** [comment]
You may want to use this: http://fieldmanager.org/docs/misc/storing-data-unserialized/
