### ISSUE TITLE
Error on update post : Sorry, you're not supposed to do that...

### ISSUE THREAD

**Issue by Energeticthemes** [alleyinteractive/wordpress-fieldmanager#384]
Hey,
I developed a slider plugin (Neat slider) base on fieldmanager. You can see it here
https://wordpress.org/plugins/neat-slider/

Some time when user delete slides from slider and update post this error appear.
"Sorry, you're not supposed to do that..." What should I do ?

I used repeatable_group for creating slides.

Thanks for great plugin.
Regards
Amjad

**Comment by dlh01** [comment]
Hi @Energeticthemes,

That error message comes from [`Fieldmanager_Field::_unauthorized_access()`](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/class-fieldmanager-field.php#L1041-L1053), which can be called from one of several places in FM.

Make sure that [`Fieldmanager_Field::debug`](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/class-fieldmanager-field.php#L30) is `true`. When Fieldmanager's debug mode is on, `_unauthorized_access()` will throw an exception with a specific error message that should help you track down the cause.
