### ISSUE TITLE
Fieldmanager_Media fields don't allow preview size to be set.

### ISSUE THREAD

**Issue by goldenapples** [alleyinteractive/wordpress-fieldmanager#387]
The [docs](http://api.fieldmanager.org/source-class-Fieldmanager_Media.html#39-45) show that it should be possible to set the preview size of a Fieldmanager_Media field to any registered image size with syntax like:

```
'featured_image' => new \Fieldmanager_Media( esc_html__( 'Featured Image' ), array(
    'name'            => 'featured_image',
    'preview_size'    => 'medium',
    'thumbnail_class' => 'variant-featured-image-preview',
    'description'     => esc_html__( 'Alternate featured media header for this variant.' ),
    ) ),
```

However, this doesn't work when initially adding the image.

The issue seems to be the inlined javascript [here](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/class-fieldmanager-media.php#L119) which defines the `fm_preview_sizes` variable as an array rather than an object. (As such, trying to set or get named properties of the object will always fail.) Changing that line to `var fm_preview_size = fm_preview_size || {};` causes media selection to respect the size chosen on initial preview.

**Comment by mboynes** [comment]
This should be fixed as of #409, but please do re-open if you're still experiencing it!
