### ISSUE TITLE
repeater group description duplicated

### ISSUE THREAD

**Issue by montchr** [alleyinteractive/wordpress-fieldmanager#390]
I'm registering a field with the code below, expecting the description to appear once at the top of the group, but instead it's repeated. I would think the description would only be repeated if applied to the children.

```php
        $containing_place = new \Fieldmanager_Group( false, [
            'name'              => 'place_contained_in',
            'description'       => esc_html__( 'A Place this Place is contained within.', 'pedestal' ),
            'limit'             => 0,
            'add_more_label'    => esc_html__( 'Add Place', 'pedestal' ),
            'add_more_position' => 'top',
            'children'          => [
                'contained_in'  => new \Fieldmanager_Autocomplete( false, [
                    'name'              => 'contained_in',
                    'attributes'        => [
                        'placeholder'   => esc_html__( 'Search by Place title', 'pedestal' ),
                        'size'          => 50,
                    ],
                    'datasource'        => new \Fieldmanager_Datasource_Post( [
                        'query_args'    => [
                            'post_type' => $place_types,
                        ],
                    ] )
                ] )
            ]
        ] );
```

![](http://cl.montchr.io/image/0r3c2z2J221b/Image%202015-10-20%20at%2017%3A02%3A20.png)

**Comment by dlh01** [comment]
That behavior seems correct to me, if I'm following. The group is the repeating field, and the description is a property of the group. That said, in practice, the repeating description has confused me too on some occasions.

Maybe there's a case for a `'repeat_description'` argument that would control the behavior? For a shorter group like your example, you could set it to `false`. For a longer group, you might include the description so the user doesn't have to find the first one again.

**Comment by danielbachhuber** [comment]
> That behavior seems correct to me, if I'm following.

I think it's expected behavior too. If you want to only display the description once, you could create a parent group with the description you want to display, and add your repeatable group to that:

```
$containing_place = new \Fieldmanager_Group( false, [
		'name'              => 'place_contained_in',
		'limit'             => 0,
		'add_more_label'    => esc_html__( 'Add Place', 'pedestal' ),
		'add_more_position' => 'top',
		'children'          => [
			'contained_in'  => new \Fieldmanager_Autocomplete( false, [
				'name'              => 'contained_in',
				'attributes'        => [
					'placeholder'   => esc_html__( 'Search by Place title', 'pedestal' ),
					'size'          => 50,
				],
				'datasource'        => new \Fieldmanager_Datasource_Post( [
					'query_args'    => [
						'post_type' => array( 'post' ),
					],
				] )
			] )
		]
	] );
$containing_place_group = new \Fieldmanager_Group( false, [
	'name'              => 'place_group',
	'serialize'         => false,
	'add_to_prefix'     => false,
	'description'       => esc_html__( 'A Place this Place is contained within.', 'pedestal' ),
]);
$containing_place_group->add_child( $containing_place );
```

![image](https://cloud.githubusercontent.com/assets/36432/13182075/dcd4ab00-d6e4-11e5-9003-10e171a5a3ba.png)

**Comment by danielbachhuber** [comment]
There's an existing issue about controlling the placement of the descriptive text #102
