### ISSUE TITLE
Surface field data in the REST API

### ISSUE THREAD

**Issue by danielbachhuber** [alleyinteractive/wordpress-fieldmanager#404]
It would be neat if I could add a `show_in_rest=>true` argument to any field (or group) I've defined, and have it automatically exposed in the REST API.

**Comment by mboynes** [comment]
Great idea. I've got another idea for FM and the REST API, so I'm going to rename this to disambiguate

**Comment by haritpanchal** [comment]
Guys, do you have any updates regarding this issue? We are using the FM and it is the blocker for us. Waiting for your response! @danielbachhuber @mboynes

**Comment by mogmarsh** [comment]
@haritpanchal what's your use case? Are you wanting fields in the REST API for admin use or for front end use? Do you need all the field data (field type, options, etc) or just the meta values?
I have started a [project](https://github.com/alleyinteractive/fm-gutenberg/) which converts FM fields into native Gutenberg controls, and as part of this makes all the field data and values available in the REST API for admin use, but not for front end use. You might be able to extract some of what you need from it.

**Comment by mboynes** [comment]
@haritpanchal see [this comment](https://github.com/alleyinteractive/wordpress-fieldmanager/issues/507#issuecomment-993994370) for a complete explanation. At this point, it's safe to conclude that we won't merge #583 to provide this functionality, for the reasons I detailed in that comment. That shouldn't be a blocker for you, however, as adding REST support to any given post or term meta, or site option, is a trivial task. And doing so from a theme or custom plugin, as I noted in that comment, will be much more stable and future-looking than depending on Fieldmanager to register the data with the REST API.

I'm going to close this issue and that PR to finally remove the ambiguity.

**Comment by haritpanchal** [comment]
@mogmarsh, We want to use the fields on the admin side, and we mostly need meta values.
