### ISSUE TITLE
1.0.0 release 

### ISSUE THREAD

**Issue by buley** [alleyinteractive/wordpress-fieldmanager#411]
Last release 1.0.0 beta2 was released Jan 15: https://github.com/alleyinteractive/wordpress-fieldmanager/releases There have been many improvements since then.

A nice and clean cutpoint is useful for packaging, for example grabbing a zip off Github during an automated build process.  

Can a codeslinger get an official 1.0 release?

**Comment by mboynes** [comment]
Absolutely. I've been dragging my feet a bit to wait for term meta to hit core, so the 1.0 release could leverage the core implementation. I have that [ready to go](https://github.com/alleyinteractive/wordpress-fieldmanager/pull/401), and we'll absolutely push an official 1.0 release in 2015.

**Comment by buley** [comment]
Excellent! Thanks for the project maintenance and development.

**Comment by danielbachhuber** [comment]
What about a bug hunt between now and pushing a 1.0 release?

**Comment by mboynes** [comment]
I decided I wanted to clear up a few more things before the 1.0 release. I'll have an RC ready next week, but I merged a bunch of things in and pushed a new beta.

> What about a bug hunt between now and pushing a 1.0 release?

@danielbachhuber I'm game for that! I've never organized one, what's the best way to go about it?

**Comment by danielbachhuber** [comment]
> we'll absolutely push an official 1.0 release in 2015.

Famous last words :)

@buley We're bug hunting today and tomorrow. I've added you to the `#fieldmanager-contrib` channel on the WordPress in Enterprise Slack if you care to join us.
