### ISSUE TITLE
first_empty ignored when false inside repeating group

### ISSUE THREAD

**Issue by joshkadis** [alleyinteractive/wordpress-fieldmanager#426]
If you have a non-repeating Fieldmanager_Select inside a repeating group, setting `$field->first_empty` to `false` is ignored because `$field->is_repeating()` returns `true`. See here:

http://api.fieldmanager.org/source-class-Fieldmanager_Select.html#97

**Comment by mboynes** [comment]
This is expected/intentional behavior. Otherwise, FM wouldn't know that an empty group was, in fact, empty. See #150

**Comment by joshkadis** [comment]
True, and I guess a hidden field that keeps track of the number of groups expected would be more trouble than it's worth
