### ISSUE TITLE
Selects showing empty when first_empty is set to false

### ISSUE THREAD

**Issue by jasonbahl** [alleyinteractive/wordpress-fieldmanager#431]
If a select is a child of a repeatable element, it inherits the "is_repeatable" attribute, which is causing the select to have an empty first_item, even if "first_empty" is set to false

**Comment by mboynes** [comment]
This behavior is intentional. Further explanation can be found in #150. I'd be up for something configurable if this is still a must have for you despite the caveats.

**Comment by jasonbahl** [comment]
@mboynes so, my scenario is as follows:

I have a repeatable group. 

Inside the group are 3 selects. The first select has 2 values, and depending on the selection, either select #2 or select #3 are displayed. Either #2 or #3 are required to have a value. . .if an empty value is saved, things break in how we're using the fields. The other option was to set the selects as required to ensure the user selects a value. . .but there's another issue preventing selects from being "required" when the first value is empty (I tried submitting a PR for this a while ago here: https://github.com/alleyinteractive/wordpress-fieldmanager/pull/396)

You can see my gist here: https://gist.github.com/jasonbahl/f6d1d50e6cd5cac63352

I have comments on where I want "first_empty" to work, but it's not working. 

Maybe there's a different way to approach my field_group so is_repeatable isn't set? I need the groups to be sortable, but not necessarily repeatable as there's a minimum and maximum number of 8 groups that need to be configured (at least for now). . .so there's no need to be able to repeat, as in "add/remove" but they do need to be sortable still. . .
