### ISSUE TITLE
add_term_form() appears on create view but not edit view

### ISSUE THREAD

**Issue by brokenhd** [alleyinteractive/wordpress-fieldmanager#436]
While working on a VIP project, my custom taxonomies have fields added using add_term_form(), and was working, but sometime within the last few weeks the fields are missing from the edit view.

**Comment by giafrata** [comment]
Just to know, I've noticed same issue, may help you to know that in VIP production env category edit page has a different url than VIP quickstart local develop env.

**VIP** : `wp-admin/edit-tags.php?action=edit&taxonomy=category&tag_ID=418146519&post_type`
**VIP quickstart** : `wp-admin/term.php?taxonomy=category&term_id=7237&post_type=post`

so I think there are two different wp versions running in local and production... but how can we display metaboxes in both wp installations? Please let us know about it.

**Comment by mboynes** [comment]
[There is a check for this](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/fieldmanager.php#L356-L358) in the current `master`. We might include it in the next release, I've just been waiting to see movement on https://core.trac.wordpress.org/ticket/34988 to see if it gets reverted.

**Comment by mboynes** [comment]
I'm keeping it in there, so I'm considering this closed. I'll remove it if core pulls that change.
