### ISSUE TITLE
Action parameters missing from beta branches

### ISSUE THREAD

**Issue by johnbillion** [alleyinteractive/wordpress-fieldmanager#437]
In 6f8980d, `$type` was added as a parameter to the `fm_{$context}` action, and the `fm_{$context}_{$type}` action was added. This change has so far not made it into the `1.0.0-beta*` branches, including beta3.

Can this be merged in please?

<3

**Comment by danielbachhuber** [comment]
@johnbillion Why not just use the master branch for now?

**Comment by johnbillion** [comment]
That's what we're doing currently.

**Comment by danielbachhuber** [comment]
Ah. I think we'll get a beta4 tagged tomorrow or early next week.
