### ISSUE TITLE
Filterable usage of core term meta

### ISSUE THREAD

**Issue by philipjohn** [alleyinteractive/wordpress-fieldmanager#438]
It might be the case that while a WP install has the term meta loveliness from core available, it doesn't work (maybe the infrastructure isn't there, for example). In this case, it'd be helpful if the decision to use core vs FM term meta could be filtered to ensure that core term meta isn't used when it's certain to fail.

Does that sound reasonable/doable?

**Comment by mboynes** [comment]
There is [a check in place](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/class-fieldmanager-field.php#L1010-L1014) for the DB version. Do you have or foresee a situation where the DB version wouldn't line up with the infrastructure?

**Comment by danielbachhuber** [comment]
For reference, WordPress core [also does the db version check](https://core.trac.wordpress.org/browser/tags/4.4/src/wp-includes/taxonomy.php#L1571) for use of `add_term_meta()`.

**Comment by philipjohn** [comment]
> Do you have or foresee a situation where the DB version wouldn't line up with the infrastructure?

Yep! That's the situation we have on WordPress.com at the moment. Term meta functions are still available, but fail silently, which could render Fieldmanager a bit limp, y'see. 

I'd rather not hack the plugin, but I realise we're probably unusual in having this requirement.

**Comment by dlh01** [comment]
Closing after discussing with @philipjohn at WordCamp US.
