### ISSUE TITLE
How do I prevent text areas from stripping HTML?

### ISSUE THREAD

**Issue by BenChirlin** [alleyinteractive/wordpress-fieldmanager#489]
Hello. Love the plugin. I've added a text area using `Fieldmanager_TextArea` but any HTML added to the field is stripped on save. Is there a way to prevent this? I see no clear option in the docs or where this strip is occuring in the repo. Is it happening in the plugin or on the WP side? How do I prevent this bahavior? Thanks!

**Comment by bcampeau** [comment]
You can specify a `sanitize` attribute for the field that defines the function used to sanitize input on saving. By default, this is set to `sanitize_text_field`. You could change it to one of the `kses` functions as appropriate to accept HTML.

See here for reference: https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/class-fieldmanager-field.php#L119-L123

**Comment by BenChirlin** [comment]
Thanks!

**Comment by raghunathj** [comment]
I did try this but <script> tag is getting removed.
This is what i am doing
`new Fieldmanager_TextArea( 
	                    	array('label'=>'Analytics2',
	                    	'sanitize' => "wp_kses_post",
	                    	)
	                    	 )`

**Comment by dlh01** [comment]
@raghunathj `wp_kses_post()` doesn't allow `<script>` tags. You'll have to use a custom sanitization function that does allow `<script>` tags. (See also #231.)

**Comment by raghunathj** [comment]
Can you share a sample example on how we can achieve this

**Comment by dlh01** [comment]
@raghunathj Please see the Gist linked here for an example: https://github.com/alleyinteractive/wordpress-fieldmanager/issues/615#issuecomment-283768636.
