### ISSUE TITLE
Color Picker: Add a default color option

### ISSUE THREAD

**Issue by kjbenk** [alleyinteractive/wordpress-fieldmanager#490]
I think it would make sense for the color picker to except a default color option so that users can understand and revert back to the default color at anytime.  This functionality is already handled within `wpColorPicker()` [here](https://github.com/WordPress/WordPress/blob/703d5bdc8deb17781e9c6d8f0dd7e2c6b6353885/wp-admin/js/color-picker.js#L149-L155).

**Comment by mboynes** [comment]
I think this already works if you set the `data-default-color` attribute

**Comment by kjbenk** [comment]
Correct you can set this attribute and the color picker will use a default color button instead of a clear button, but I wanted to create a way for the developers to specify this via the PHP constructor.  So that they can do something like this:

``` php
$fm = new Fieldmanager_Colorpicker( array( 'name' => 'default_colorpicker', 'default_color' => '#ff0000' ) );
```

I created a quick PR for this 😄

**Comment by dlh01** [comment]
Added in #491.
