### ISSUE TITLE
does display_if work with Fieldmanager_Group?

### ISSUE THREAD

**Issue by montchr** [alleyinteractive/wordpress-fieldmanager#497]
I'd like to use `display_if` to hide/show a Group based on the value of a field in a neighboring Group. From what I can tell, this isn't possible — the `.display-if` class isn't even added to the Group `div` — but maybe I'm missing something.

Edit: I should add that when I do try adding `display_if` to a Group, I get this JS error:

```
Uncaught TypeError: Cannot read property 'split' of undefined
.../fieldmanager/js/fieldmanager.js?ver=1.0.7 line 226
```

If it's not supported — how much of a lift would it be to add this functionality?

**Comment by pbearne** [comment]
yes is does

`$fm = new \Fieldmanager_Group( array(
			'name'     => 'template',
			'children' => array(
				'has_sub_blog' => new \Fieldmanager_Checkbox( array(
					'name'  => 'has_sub_blog',
					'label' => __( 'Has sub-blog', 'cbi' )
				) ),
				'image'        => new \Fieldmanager_Media( __( 'Header bckground Image', 'cbi' ), array(
					'display_if' => array(
						'src'   => 'has_sub_blog',
						'value' => 'true',
					),
				) ),
				'featured'     => new \Fieldmanager_Group( array(
						'display_if'                => array(
							'src'   => 'has_sub_blog',
							'value' => 'true',
						),` .....

you will need to close the array
