### ISSUE TITLE
Some settings not being preserved when upgrading from 1.0.0-beta.2 to 1.0.0

### ISSUE THREAD

**Issue by jamesmehorter** [alleyinteractive/wordpress-fieldmanager#501]
Hey hey, just updated my local to use the release candidate of Fieldmanager (on wpcom VIP, using the RC version by changing `wpcom_vip_load_plugin( 'fieldmanager' );` to `wpcom_vip_load_plugin( 'fieldmanager', 'plugins', true );`) which does retain most of the existing FM data, but is not currently retaining data created with the Fieldmanager_Datasource_Term datasource (copying data from the hidden fm-term-meta post meta to term meta).

Feel free to message me on Slack for details on where this is occurring.

**Comment by mboynes** [comment]
Issue here was a custom context
