### ISSUE TITLE
Repeatable grids don't work

### ISSUE THREAD

**Issue by mboynes** [alleyinteractive/wordpress-fieldmanager#51]

**Comment by mparfait** [comment]
Hello everyone, thanks for this awesome plugin ! 
I just have but one question...
I used a multiple group fields with a "normal field" and a "grid field". The normal field is ok but not the grid field. (Look at the screenshot)
I found this post, I thinked it was the good one.

Best regards,

![bug data grid](https://cloud.githubusercontent.com/assets/11042023/6225931/a1c7b504-b690-11e4-9f71-ab6399a05507.png)
