### ISSUE TITLE
Add_another() use case

### ISSUE THREAD

**Issue by ConnectedCat** [alleyinteractive/wordpress-fieldmanager#519]
I could find not examples of how add_another method of a Fieldmanager_Field object could be used. I'm trying to do this:
```
add_action( 'fm_post_publication', function(){
$publication_group = new Fieldmanager_Group( array(
    'name' 			=> 'publication_addition_info',
    'children' 	=> array(
      'field-one' 	=> new Fieldmanager_TextField( 'Conference Name' ),
			'field-two'		=> new Fieldmanager_Autocomplete(
				'Authors',
				array(
					'show_edit_link' => true,
					'datasource' => new Fieldmanager_Datasource_Post( array(
						'query_args' => array( 'post_type' => 'researcher' ),
					) ),
					'add_more_label' => 'Add Another Author',
					'add_more_position' => 'bottom'
				)
			) // end of field-two
		) // end of children
	));
	$publication_group->children['field-two']->add_another();
	$publication_group->add_meta_box( 'Additional Information', 'publication');
} );
```
this produces no results.
When I try to
```
echo $publication_group->children['field-two']->add_another();
```
The HTML element appears as the very first thing in the body - expectedly - and it is not connected to the field or the form in any way. What's the proper use of this functionality?

**Comment by mboynes** [comment]
`add_another()` is not necessarily meant to be called directly. To make a repeating field, set `'limit' => 0` in the field args to make it indefinitely repeatable, or set `'limit'` to a ceiling, e.g. `'limit' => 5`. This will automatically add the "Add another" button for you.

**Comment by mboynes** [comment]
BTW, check out https://github.com/alleyinteractive/fieldmanager-demos/ for an extensive set of demos.
