### ISSUE TITLE
adding meta boxes to custom post types

### ISSUE THREAD

**Issue by JohnEcks** [alleyinteractive/wordpress-fieldmanager#520]
This may be basic but I'm not a programmer so hopefully you can point out the obvious.

I setup a custom meta box with multiple options for 2 custom post types (WordPress 4.6). It loads fine on the creation and edit pages.

I wanted to know how you can move the meta box directly below the content area. As it is now it appears below the core stuff, like comments, trackbacks, etc. Right now in Screen Options it's listed 6th, so I assume that's the order things are being displayed.

thanks

if it matters, here's the code I'm using in functions:

```php
// Add Meta Boxes from Field Manager
function my_media_box() {
	$fm = new Fieldmanager_Group( array(
		'name' => 'media_information',
		'children' => array(
			'short_description' => new Fieldmanager_TextArea( 'Short Description' ),
			'long_description' => new Fieldmanager_TextArea( 'Long Description' ),
			'splurge_description' => new Fieldmanager_TextArea( 'Splurge Description' ),
			'duration' => new Fieldmanager_Textfield( 'Duration' ),
			'youtube_id' => new Fieldmanager_Textfield( 'YouTube ID' ),
			'transcript' => new Fieldmanager_Textfield( 'Transcript File Name' ),
		),
	) );
	$fm->add_meta_box( 'Media Information', array('audioz', 'videoz') );
}
add_action( 'fm_post_audioz', 'my_media_box' );
add_action( 'fm_post_videoz', 'my_media_box' );
```

**Comment by mboynes** [comment]
Hey @JohnEcks, happy to answer that for you. Before I do, it's important to point out that Fieldmanager is entirely aimed at programmers, so if you're not a programmer, you might want to consider a different plugin.

Having said that, [the `add_meta_box()` method](http://api.fieldmanager.org/source-class-Fieldmanager_Field.html#1032-1048) accepts two more arguments, `$context` and `$priority`, which match [WordPress core's functionality](https://developer.wordpress.org/reference/functions/add_meta_box/). If you set the priorty to `'high'`, I think that will put the meta box where you want it:

```php
$fm->add_meta_box( 'Media Information', array('audioz', 'videoz'), 'normal', 'high' );
```

**Comment by JohnEcks** [comment]
thanks for the reply. I'll try it out.

Yeah I'm not a programmer, but I've absorbed enough for my project (luckily). Just the basics of field manager seem to be allowing me to do what I need without writing tons of code to make custom meta boxes in my functions file. It's just for organizing the custom fields I already have into a simple UI, and it seems to be working. :)

cheers

**Comment by mboynes** [comment]
Glad to hear it! Be sure to check out http://fieldmanager.org/docs/ if you haven't already, as well as [the demo plugin](https://github.com/alleyinteractive/fieldmanager-demos), which provides examples of about 80% of what Fieldmanager can do.

**Comment by JohnEcks** [comment]
Yeah I've been reading the docs. I'll checkout the demo plugin.

thanks so much for sharing this software. It's going to save me a few ulcers.
