### ISSUE TITLE
simple dividers / sub-groups

### ISSUE THREAD

**Issue by DhatesCode** [alleyinteractive/wordpress-fieldmanager#529]
Hi guys

Is there a simple way to add dividers into a fieldmanager metabox, or to subgroup things that are in tabbed groups?

An example would be to group a checkbox and a text field that are children in a tab of a vertical tabbed group and maybe adjust background color and/or have `border-bottom` attributes.

Would be cool to even be able to define a divider after a Fieldmanager element with an optional class if doing admin styling. Something like:

``` php
'divider' => array(
    'width' => 50%,
    'thickness' => 1px,
    'type' => 'solid',
    'color' => #555,
    'class' => 'meta-divider',
),
```

thanks

**Comment by dlh01** [comment]
Customizing the `Fieldmanager_Field::field_class` property, or filtering `fm_element_markup_(start|end)`, and applying custom styles in your own CSS might be the most straightforward way to accomplish this.

You might also want to keep an eye on the proposed UI updates in the [fm-ui-update branch](https://github.com/alleyinteractive/wordpress-fieldmanager/tree/fm-ui-update) to see whether they help improve the styles around your fields.
