### ISSUE TITLE
Fields on a specific page

### ISSUE THREAD

**Issue by jmusal** [alleyinteractive/wordpress-fieldmanager#539]
I've looked at the documentation, but I think I'm striking out.  Is there a way to associate a group only with a specific page / post?

**Comment by dlh01** [comment]
Hi @jmusal,

There isn't currently native support for that, as far as I'm aware. I think the most common workaround is to get the post ID from `$_GET` and `$_POST` and check what you need to before instantiating your field, but others might be able to suggest a better approach.

**Comment by jmusal** [comment]
Thanks, that seems to be doing the job just fine.
