### ISSUE TITLE
Why append = at the start of the string?

### ISSUE THREAD

**Issue by AlexAlexandru** [alleyinteractive/wordpress-fieldmanager#547]
What's up with this line?
https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/js/fieldmanager-autocomplete.js#L74

I have deleted the appended = and it works but I don't wan't thing to break later so this is why I ask.

**Comment by mboynes** [comment]
[Here's the other end of it](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/datasource/class-fieldmanager-datasource-term.php#L161-L164). It needs to be refactored, but it shouldn't be removed without a replacement.

Duplicates #395.
