### ISSUE TITLE
Fieldmanager_Autocomplete, Fieldmanager_Datasource_Post, and tax_query

### ISSUE THREAD

**Issue by doubleswirve** [alleyinteractive/wordpress-fieldmanager#552]
Hello,

Using Fieldmanager plugin on WP VIP (latest available in SVN plugins repo). Trying the following:

```php
( new \Fieldmanager_Group( array(
    'name' => 'cats',
    'limit' => 0,
    'label' => 'Category',
    'label_macro' => array( 'Category: %s', 'title', ),
    'add_more_label' => 'Add another category',
    'collapsed' => true,
    'sortable' => true,
    'children' => array(
        'title' => new \Fieldmanager_Textfield( 'Title' ),
        'people' => new \Fieldmanager_Autocomplete( array(
            'label' => 'People',
            'limit' => 0,
            'sortable' => true,
            'add_more_label' => 'Add another Person',
            'datasource' => new \Fieldmanager_Datasource_Post( array(
                'query_args' => array(
                    'post_type' => 'my-people',
                    'posts_per_page' => 100,
                    /* Important part */
                    'tax_query' => array(
                        array(
                            'taxonomy' => 'personality',
                            'field' => 'slug',
                            'terms' => 'friendly',
                        ),
                    ),
                    /* /Important part! */
                ),
            ) ),
        ) ),
    ),
) ) )->add_meta_box( 'Categories', 'my-post-type', 'normal', 'high' );
```

When testing this out, I'll receive a response body of `0` with a content type of `text/html`. There's also a JavaScript error thrown: `Uncaught TypeError: Cannot use 'in' operator to search for 'length' in 0 jquery.js?ver=1.12.4:2`. No PHP errors.

If I comment out the `tax_query` portion of the `query_args` __or__ if I add the `use_ajax` property and set it to `false`, the datasource works with the correct autocomplete results.

Thanks!

**Comment by dlh01** [comment]
Whenever I get that `0` response, it's usually because the datasource isn't instantiated during the Ajax request. When does the code in your snippet run (e.g., if during an action, which action)?

**Comment by doubleswirve** [comment]
I'm setting up the meta boxes and adding the datasource in the `init` action. Also using PHP 7. Thanks!

**Comment by dlh01** [comment]
I'm unable to replicate the issue using the snippet you posted, so I'm not sure how much help I can be, unfortunately. 

I would make sure there isn't a doing-Ajax check wrapping your code, like `if ( is_admin() && ( ! defined( 'DOING_AJAX' ) || ! DOING_AJAX ) ) add_action( 'init' ... )`. 

You might also consider moving from `init` to a Fieldmanager context action, which will ensure your field is instantiated only when necessary. Browse [the source](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/fieldmanager.php#L379) or [Fieldmanager demos](https://github.com/alleyinteractive/fieldmanager-demos) if you need more information about those.

**Comment by doubleswirve** [comment]
Sounds good - thanks for looking into it!

**Comment by dlh01** [comment]
Feel free to keep this issue open if you think there's still a problem, @doubleswirve, especially if you're not able to find a cause for what's happening. There might still be a bug here, and I didn't mean to imply otherwise. Other folks still might be able to replicate the behavior or provide more insight.

**Comment by doubleswirve** [comment]
I took another look at this tonight and I'm pretty sure the issue is on my end. I was trying to set up the autocomplete field conditionally based on the main post's category (not mentioned in the original snippet). It looks like the condition, although succeeding in the original admin page load, fails during the Ajax request. This seems to back up your theory of the datasource not being instantiated.

I think I could work around this via a combination of `$custom_args_js_event` and `$query_callback`; however, using the `$use_ajax` option set to `false` should work fine for our use case since we'll never be querying large datasets for an autocomplete match.

Thanks again for your help and time
