### ISSUE TITLE
Large sortable list not saving the correct order when changed

### ISSUE THREAD

**Issue by Sitetools** [alleyinteractive/wordpress-fieldmanager#553]
I have created a sortable list:

        $pb9 = new Fieldmanager_Group( array(
                'name' => 'model_package',
                'limit' => 0,
                'label' => 'Model Package',
                'collapsed' => true,
                'label_macro' => array( 'Package: %s', 'title' ),
                'sortable' => true,
                'add_more_label' => __( 'Add another package', 'title' ),
                'children' => array(
                        'heading' => new Fieldmanager_Checkbox( array('name' => 'heading',
                                                    'label' => 'Package heading',
                                                ) ),
                        'title' => new Fieldmanager_Textfield( 'Attribute title' ),
                        'img' => new Fieldmanager_Media( 'Link image if needed' ),
                        'gl' => new Fieldmanager_Textfield( 'GL value' ),
                        'sport' => new Fieldmanager_Textfield( 'Sport value' ),
                        'limited' => new Fieldmanager_Textfield( 'Limited value' )
                ),
        ) );
        $pb9->add_meta_box( 'Model Package', array( 'models' ) );

I have done this many times, but this list is much longer than any other I have done before around 100 list items.
When I move an item to another position and save the post the moved item has saved in a different position, usually 1 below the position it was moved to.
I have removed any characters from the input fields that might be causing issues e.g. &,'() etc.

Can you think of anything I can try to resolve this issue?

**Comment by dlh01** [comment]
I can replicate this behavior, but, in my case, I'm not sure the cause was the length of the list. 

In my testing, the `name` attribute of the checkbox's companion `hidden` input was not being renumbered after resorting group children, no matter how many children were in the group. 

When the misnamed input was submitted, the resulting `$_POST['model_package']` array was out of order (`98`, `100`, `99`...) and would be saved as such.

The unchanged `hidden` input seems like it could be a bug, although I might be overlooking something. While I don't know how generalizable the cause-and-effect is, if I remove the `Fieldmanager_Checkbox`, or if I change [`fm_renumber`](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/js/fieldmanager.js#L80) to `$( this ).find( '.fm-element, .fm-item > input[type=hidden], .fm-incrementable' )`, then seems resorting works as expected.

**Comment by Sitetools** [comment]
Thanks for that, I'll do some testing and let you know how I get on.
I love this plugin, you have allowed me to create intuitive pages and posts for clients.

Thank you for sharing your plugin.

**Comment by Sitetools** [comment]
Great stuff, I used the $( this ).find( '.fm-element, .fm-item > input[type=hidden], .fm-incrementable' ) to replace $( this ).find( '.fm-element, .fm-incrementable' )
Worked perfectly once I'd hard refreshed the page.

Thank you.

**Comment by dlh01** [comment]
I'm glad to hear it, although I wouldn't rely on that particular piece of code without (at least) more research into its effects on the rest of Fieldmanager, unit tests, and feedback from others. But, I hope it helps with identifying the issue, if in fact it's an FM issue, and finding a solution.

**Comment by amehta3000** [comment]
I'm seeing the same issue. Sorting is only working when I don't have a checkbox in the children array. I had to just comment out my checkbox and then the sortable started working again.  It is obviously not desirable and seems like a bug. If there is another work around? 

```
$pli => new \Fieldmanager_Group( 'Playlist Item', array(
	'limit'          => 0,
	'add_more_label' => 'Add Playlist Item',
	'sortable'       => true,
	'collapsible'    => true,
	'collapsed'      => true,
	'extra_elements' => 0,
	'label'          => 'Playlist Item',
	'children'       => array(
		// 'hide_video'    => new \Fieldmanager_Checkbox( 'Hide Video' , array(
		// 	'default_value' => 0
		// 	) 
		// ),	
		'title'        => new \Fieldmanager_Textfield( 'Title' ),
		'description' => new \Fieldmanager_TextArea( 'Description', array(
				'attributes' => array(
					'rows' => 3,
					'cols' => 50,
					),
			)
		),
		'mediaURL'         => new \Fieldmanager_Link( 'Media URL', array(
			'description' 	=> 'Enter URL to m3u8 file'
			) ),
		'thumbnail'       => new \Fieldmanager_Media( 'Thumbnail', array(
			'description' 	=> 'Thumbnail should be 16:9 aspect ratio for best fit.'
			) ),
	)
) )
```
