### ISSUE TITLE
Fieldmanager_Context_Page documentation?

### ISSUE THREAD

**Issue by montchr** [alleyinteractive/wordpress-fieldmanager#566]
I've been looking into using `Fieldmanager_Context_Page` for adding forms to an arbitrary admin page, but noticed the lack of documentation regarding this class (besides looking at source directly). How do I get started using this feature?

I'd initially tried using `Fieldmanager_Context_Submenu`, but I need to be able to customize the rendered page further, which it seems FM doesn't allow.

I also came across #157, which was referenced in #211 as a replacement for `Fieldmanager_Context_Page`. What are the benefits of that approach over using `Fieldmanager_Context_Page`? And is there a timeline for merging #211?

**Comment by montchr** [comment]
`Fieldmanager_Context_Page::render_page_form()` uses `$this->fm->submit_button_label`. In the constructor, `$this->fm` is documented as being an object of class `Fieldmanager_Field`. But that class does not define a `submit_button_label` property, and as far as I can tell, the only class that does is `Fieldmanager_Context_Submenu`. But it doesn't really make sense to pass that as `$fm`, especially when the inline documentation asks for `Fieldmanager_Field`. So I'm at a bit of a loss here.

**Comment by dlh01** [comment]
`Fieldmanager_Context_Page` is going to be deprecated in the 1.2.0 release, and #157 is currently targeted for the 1.3.0 release. I would say the primary benefit of using #157 at this point is just that it'll be better supported than `Fieldmanager_Context_Page` has been once it's in. If you're able to try out #157, then any feedback you could provide would be very helpful.
