### ISSUE TITLE
Validation functions

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [alleyinteractive/wordpress-fieldmanager#578]
Hello!
I am testing out all kinds of free WordPress custom meta box plugins that support nested and zero-length repeaters and custom validation. I would like to know if there is a way I can return a validation error if one field in each child of a repeating group is greater than another, and display the error message on the group as a whole.

Another text field of another group needs to be required, but only if the group's length is greater than 1. Can you help me with this?

**Comment by dlh01** [comment]
Hi @ssimo3lsuhsc,

One way to accomplish this might be to extend [`Fieldmanager_Group::presave()`][0] in a child class with your custom validation logic. Another might be to inspect the submitted values during the [`fm_presave_alter_values`][1] filter. I'm sure other folks have used Fieldmanager in other ways to achieve similar functionality, too. 

Validation errors are usually broadcast by [`Fieldmanager_Field::_failed_validation()`][1]. See #534 for a discussion about potential future validation frameworks.

[0]: https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/class-fieldmanager-group.php#L301
[1]: https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/class-fieldmanager-field.php#L853
[2]: https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/class-fieldmanager-field.php#L1126

**Comment by sasimon** [comment]
dlh01:
I understand how I can override Fieldmanager_Group::presave(). What I really want is an example of how I can control where the errors are shown on the page. Something like this (written in my own pseudocode):

Numbers (class extending Fieldmanager_Group):
Row 1:
(no error)
First number: 2
Second number: 3

Row 2:
Error! Second number must be greater than first.
First number: 10
Second number: 8

Note how the error is shown in Row 2 but not Row 1.

**Comment by dlh01** [comment]
A few possibilities I can think of:

- The `fm_element_markup_start` filter would allow you to insert markup at the beginning of a group.

- The `Fieldmanager_Field::template` property would allow you to use a custom template for fields within the group, where you could include errors.

- `Fieldmanager_Group::form_element()` could also be overridden to prepend markup.
