### ISSUE TITLE
how to control the Fieldmanager_Grid rows and cols in meta box

### ISSUE THREAD

**Issue by iwillhappy1314** [alleyinteractive/wordpress-fieldmanager#579]
by defailt, the Fieldmanager_Grid show 5cols and 5 row, how to custom the count of rows and cols?

is there some docs?

**Comment by kjbenk** [comment]
Have you tried to use the `attributes` variable to set the cols and rows?

https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/class-fieldmanager-field.php#L96-L100

**Comment by iwillhappy1314** [comment]
Found the example code here: https://github.com/alleyinteractive/fieldmanager-demos/blob/master/lib/class-fm-demo-grid.php
