### ISSUE TITLE
Multiple `display_if` values for a given field?

### ISSUE THREAD

**Issue by kkoppenhaver** [alleyinteractive/wordpress-fieldmanager#618]
Use case: A dropdown with three options and three text fields underneath.

The first box is always visible no matter which dropdown option is selected.
The second box is visible if option 2 OR option 3 is selected.
The third box is visible only if option 3 is selected.

A workaround I've used in the past is to create 3 separate field groups: one with one textbox, one with two text boxes, and one with all three.  This requires duplication in fields as well as jumping through more hoops on the display end.

What I need for text field #2 to function as intended is to be able to pass an array of possible options to `display_if`:

`'display_if' => [
	'src' => 'column_count',
   	'value' => array( 'two', 'three' ),
]`

where column_count being `two` OR `three` will make the field visible.

Relevant code is at php/class-fieldmanager-field.php:448-453 and js/fieldmanager.js:202-270.

Happy to work on a PR as this is something I've encountered on a couple different projects.

**Comment by dlh01** [comment]
Hi @kkoppenhaver, 

If I understand you correctly, I think this is possible now by comma-separating the values: `two,three`.

**Comment by kkoppenhaver** [comment]
@dlh01 Works perfectly, thanks! Going to write up a quick post about this, but is there anywhere I can add this to the documentation or somewhere I should have found it?

**Comment by dlh01** [comment]
I don't see a mention of it in the existing docs, although maybe I'm also overlooking it. But if it's missing, then amending the example in the `display_if` property docs would make sense to me.

**Comment by kkoppenhaver** [comment]
@dlh01 Submitted that PR for documentation update.  Travis is failing out on some unrelated files, which I've documented on the PR.

**Comment by dlh01** [comment]
Fixed in 1.2.0.
