### ISSUE TITLE
Data not saved in fm_post_page

### ISSUE THREAD

**Issue by saroj38** [alleyinteractive/wordpress-fieldmanager#626]
add_action( 'fm_post_post', function() {
	  $fm = new Fieldmanager_Group( array(
	    'name' => 'adCampaign1',
	    'children' => array(
	      'name' => new Fieldmanager_RichTextarea( 'Name' ),
	  ) )
	  );
  	  $fm->add_meta_box( 'Name','post' );
});
The data is saved in this function but in the below function the user entered data in not saved in the metabox. Can someone help me please?

add_action( 'fm_post_page', function() {
	  $fm = new Fieldmanager_Group( array(
	    'name' => 'adCampaign1',
	    'children' => array(
	      'name' => new Fieldmanager_RichTextarea( 'Name' ),
	  ) )
	  );
  	  $fm->add_meta_box( 'Name','page' );
});

**Comment by saroj38** [comment]
Can someone help me out?

**Comment by dlh01** [comment]
@saroj38 I'm unable to replicate this behavior using the code you provided, unfortunately. Do you know what version of WordPress, Fieldmanager, and PHP you're using? Are you able to deactivate other plugins to see whether they're interfering with saving data?

**Comment by dlh01** [comment]
Closing for lack of feedback. Please feel free to reopen if you're able to provide additional diagnostic information.
