### ISSUE TITLE
Refresh Nonce Values After Reauthenticating To Prevent Data Loss

### ISSUE THREAD

**Issue by kingkool68** [alleyinteractive/wordpress-fieldmanager#627]
## Problem
When an authenticated session expires and a user logs in again the FieldManager nonce fields should refresh as well. The way things work now is when you reauthenticate everything seems fine so a user may continue adding content. When the post is eventually saved the user is presented with a `wp_die()` screen letting them know something is wrong (because behind the scenes the nonce verification failed). All of their previous work is lost after this happens.

This has happened to our editorial team a number of times and it is painful to hear how they lose work whenever it happens. 

## Suggested Solution
WordPress provides a filter, `wp_refresh_nonces`, for sending new nonces to the editor after reauthenticating. You can see an example of how this is used in the `wp_refresh_post_nonces()` function in `/wp-admin/includes/misc.php`.  You provide a key => value pair with the key being the ID attribute of the nonce and the value being the new nonce value. WordPress should handle doing the replacement for you in `post.js`. 

## Steps to Reproduce
 - Create a new post with one or more FieldManager fields
 - Save the post as a draft
 - Make more content changes
 - Delete the domain cookies to force WordPress to reauthenticate via the Heartbeat API
 - Reauthenticate
 - Save the post and be presented with an error screen and all your changes are gone

**Comment by mboynes** [comment]
Thanks for the excellent writeup!

We'll need a solution that works across all contexts. Hopefully core makes that easy, but I've not looked into it. If anyone has time to take this on, please do. Otherwise, I might not be able to get to it until next month or even later.

**Comment by dlh01** [comment]
We expect that #677 will address this issue, excepting the limitations in the block editor and non-post contexts described in the PR. If not, please reopen with the details!
