### ISSUE TITLE
Update get_terms call in Datasource Term

### ISSUE THREAD

**Issue by brshewmaker** [alleyinteractive/wordpress-fieldmanager#631]
Inside `datasource/class-fieldmanager-datasource-term.php`, there is a call to `get_terms()` that uses the now deprecated 2nd argument:

`$terms = get_terms( $this->get_taxonomies(), $tax_args );`

This way of calling `get_terms` has been deprecated, see https://developer.wordpress.org/reference/functions/get_terms/ and perhaps this could be updated to reflect this.

**Comment by dlh01** [comment]
Previously: #541.
