### ISSUE TITLE
Adding New RichTextArea In Repeatable Group Locks Previous RTAs With Content, New One Is Disabled

### ISSUE THREAD

**Issue by johnstrawserjr** [alleyinteractive/wordpress-fieldmanager#636]
My fields are shown below. I've tried turning off repeatable & collapsible but when I add a new field, all the previous RTAs lose content & the last one is disabled. I can click into the new field - but the text is hidden (white). The previous fields hold their content if I save, but I can't edit them (or see the content). If I comment out `fm_renumber` function in fieldmanager.js, the previous fields stay editable with content, but the new field isn't enabled.

```
$fm = new Fieldmanager_Group([
		'name' => 'recipe',
		'serialize_data' => false,
		'children' => [
			'preparation' => new Fieldmanager_Group([
				'label' => 'Preparation Group',
				'add_more_label' => 'Add Preparation Group',
				'description' => 'Add multiple groups for multiple steps.',
				'limit' => 10,
				//'collapsible' => true,
				//'collapsed' => true,
				'children' => [
					'header' => new Fieldmanager_Textfield([
						'label' => 'Header',
						'description' => '(optional) Heading for preparation step. (Prepare Dipping Sauce)'
					]),
					'step' =>  new Fieldmanager_RichTextArea([
						'editor_settings' => simple_editor_settings(),
						'label' => 'Steps',
						'add_more_label' => 'Add Step',
						'one_label_per_item' => false,
						'limit' => 20,
						'sortable' => true,
					]),
				]
			]),
		
		]
	]);
```

**Comment by mboynes** [comment]
Hey @johnstrawserjr, thanks for the detailed report and for your initial debugging, tying it back to `fm_renumber()`. That's very helpful! I'll take a look at this, I likely have the most experience with `Fieldmanager_RichTextArea`.

**Comment by johnstrawserjr** [comment]
Please let me know if I can help any further @mboynes. I tried to find a solution, but was getting a bit lost, but happy to help with further debugging.

**Comment by dlh01** [comment]
The buggy behavior with this snippet appears to be very similar to that of #502. I'm going to close this ticket in favor of that one, and I'll leave a pointer over there to the additional snippet here that can be used for testing.
