### ISSUE TITLE
wpcom_vip_get_term_by is being deprecated.

### ISSUE THREAD

**Issue by pjpak** [alleyinteractive/wordpress-fieldmanager#637]
https://github.com/alleyinteractive/wordpress-fieldmanager/blob/ddff68e4f3cc5a11e8ca95e088be07f40ed1ee07/php/datasource/class-fieldmanager-datasource-term.php#L167

**Comment by dlh01** [comment]
Hi @pjpak -- would you like to submit a PR that updates calls to `wpcom_vip_get_term_by()`?

**Comment by pjpak** [comment]
Hi, that sounds good. I dont see a develop branch, can I do PR against master? thanks

**Comment by dlh01** [comment]
Against `master` is fine.

**Comment by mboynes** [comment]
Resolved in #645
