### ISSUE TITLE
Unable to make a required field for fieldmanager_media

### ISSUE THREAD

**Issue by raghunathj** [alleyinteractive/wordpress-fieldmanager#668]
I have been trying to make sure a particular field to make it a mandatory, and also tried some of the approaches mentioned in the previous issues but nothing is working. Can you guys let me know how we can make it happen.

`new Fieldmanager_Media([
							'label' => 'PDF File',
							'mime_type' => 'application/pdf',
							'validation_rules' => array('required'=> true ),
            'validation_messages' => array('required'=> 'This is mandatory' ),
							])`

**Comment by dlh01** [comment]
Duplicate of #526. 

@raghunathj even if you've tried approaches mentioned in that issue, I think it would be preferable to keep the discussion there because the people who are watching the issue might see your message and be able to help.
