### ISSUE TITLE
'required' => true, not working on FM Link or TextField

### ISSUE THREAD

**Issue by dariozac** [alleyinteractive/wordpress-fieldmanager#680]
```
        (new \Fieldmanager_Textfield([
          'name' => 'link_to',
          'required' => true
          ]))->add_meta_box('Links To:', ['offer'], 'after_title', 'high');
```
The above ``` 'required' => true,``` is not working on at least TextField and Link, any help appreciated

**Comment by dlh01** [comment]
@dariozac According to the docs, the `required` attribute works on only the term context: https://github.com/alleyinteractive/wordpress-fieldmanager/blob/14a78c99c30a81b93494d1b4990a113e9f9f4803/php/class-fieldmanager-field.php#L181-L187.

You might want to try passing the HTML5 `required` attribute to your field using the `attributes` property. The jQuery Validation library is also available through the `validation_rules` property.

**Comment by dariozac** [comment]
Hi @dlh01,

Many thanks for the response. Got the intended outcome with the following

`'validation_rules' => ['required' => true, 'url' => true]`
