### ISSUE TITLE
Cannot save empty multi-select when serialize_data is false

### ISSUE THREAD

**Issue by discoinfiltrator** [alleyinteractive/wordpress-fieldmanager#685]
I am using the multiselect (w/ chosen) to implement taxonomy term selection for posts:

```
$tax = new Fieldmanager_Select(
    [
        'label' => 'My Taxonomy',
        'type_ahead' => true,
        'multiple' => true,
        'datasource' => new Fieldmanager_Datasource_Term(
            [
                'taxonomy' => ['my_taxonomy_name'],
                'only_save_to_taxonomy' => true,
                'taxonomy_hierarchical' => true,
            ]
        )
    ]
);
$fm = new Fieldmanager_Group([
    'name' => 'my_group_name',
    'add_to_prefix' => false,
    'serialize_data' => false,
    'description_after_element' => false,
    'children' => [
        'my_taxonomy_name' => $tax,
    ],
]);
$fm->add_meta_box('Taxonomies (required)', ['post']);
```

I was running into a bug:

1. Add a taxonomy to a post, save.
2. Edit post, remove taxonomy, save.
3. Notice that post is saved, but taxonomy was not removed.

After digging through the code, the cause was that when serialize_data is true, we execute this code in the Fieldmanager_Context_Storable, save:

```
$data = isset( $_POST[ $this->fm->name ] ) ? $_POST[ $this->fm->name ] : '';
```

This is an issue for multi-selects and radio buttons.  Multiple select and radio fields with no values chosen are left out of the post request altogether. I've come up with a solution and will submit a PR.

**Comment by discoinfiltrator** [comment]
PR is:

#686

**Comment by dlh01** [comment]
I've added this to our new milestone for Fieldmanager 1.4.0 in light of our observation that #764, also in the milestone, reports essentially the same issue but with checkboxes. As noted there, we might want to look into expanding the fix to cover that additional case, although I wouldn't want to cause any undue delay to resolving this issue as a result.

**Comment by discoinfiltrator** [comment]
Hey @dlh01 , whatever works for you. We won't be able to upgrade right away anyway, so if you have an alternative solution that covers both cases, sounds great to me. 👍
