### ISSUE TITLE
Repeater field saving empty rows

### ISSUE THREAD

**Issue by spacedmonkey** [alleyinteractive/wordpress-fieldmanager#688]
We have a repeater field. Every time a user saves the post, it will add an empty row on the end of field. This happens every time a users saves. See screenshot. 

![screenshot from 2018-01-26 14-57-24](https://user-images.githubusercontent.com/237508/35445865-ee14e18e-02aa-11e8-8dd1-edd810951868.png)

If required, I can provide the php we used to generate the fields. We are using FM: 1.2.1

Possibly related: #687

**Comment by dlh01** [comment]
Hey @spacedmonkey — yes, if you could provide the PHP for the fields, that would be very helpful.

**Comment by mstudio** [comment]
Hi there @dlh01. I'm having the exact same issue. Each time I save a post, an empty field is added to the Group "content_blocks". My full code is below. Please let me know if you need anything else. Thank you!

`

	class DemoTech_Fields_Article {

		private static $instance;

		private function __construct() {
			/* Don't do anything, needs to be initialized via instance() method */
		}

		public static function instance() {
			if ( ! isset( self::$instance ) ) {
				self::$instance = new DemoTech_Fields_Article;
				self::$instance->init();
			}
			return self::$instance;
		}

		public function init() {

				$fm = new Fieldmanager_Group(
					array(
						'name'     => 'article_type',
						'children' => array(
							'article_conditional'   => new Fieldmanager_Select(
								array(
									'options' => array(
										'standard'  => 'Standard',
										'slideshow' => 'Slideshow',
									),
								)
							),
							// Copy
							'copy' => new Fieldmanager_RichTextArea(
								false,
								array(
									'label' => 'Copy Above Slideshow',
									'display_if' => array(
										'src'   => 'article_conditional',
										'value' => 'slideshow',
									),
									'attributes'      => array( 'style' => 'width:100%' ),
									'editor_settings' => array(
										'media_buttons' => false,
									),
								)
							),
							// Image Block and Caption
							'image'               => new Fieldmanager_Group(
								array(
									'label'      => 'Slideshow Images',
									'display_if' => array(
										'src'   => 'article_conditional',
										'value' => 'slideshow',
									),
									'children'   => array(
										'images' => new Fieldmanager_Group(
											array(
												'tabbed'   => true,
												'limit'    => 20,
												'add_more_label' => 'Add another Image',
												'sortable' => true,
												'collapsible' => true,
												'collapsed' => true,
												'children' => array(
													'image-hi' => new Fieldmanager_Media( 'Image' ),
													'caption'          => new Fieldmanager_TextArea(
														array(
															'label' => 'Caption',
															'attributes' => array( 'style' => 'width:100%' ),
														)
													),
												),
											)
										),
									),
								)
							),
						)
					)
				);
				$fm->add_meta_box( 'Article Type', 'post' );

				// Blurb
				$fm = new Fieldmanager_TextArea(
					false, array(
						'name'       => 'blurb',
						'attributes' => array( 'style' => 'width:100%' ),
					)
				);
				$fm->add_meta_box( 'Blurb', 'post' );

				// Hero
				$fm = new Fieldmanager_Group(
					array(
						'name'     => 'hero',
						'children' => array(

							'hero_conditional'   => new Fieldmanager_Select(
								array(
									'label'   => 'Hero Type',
									'options' => array(
										'none'  => 'None',
										'image' => 'Image',
										'fb'    => 'Facebook Video',
										'yt'    => 'YouTube Video',
										'vm'    => 'Vimeo Video',
									),
								)
							),

							// Image
							'image'              => new Fieldmanager_Media(
								'Image',
								array(
									'label'        => 'Image',
									'description'  => 'Upload an image',
									'preview_size' => 'medium',
									'display_if'   => array( // This works on most, but not all field types
										'src'   => 'hero_conditional', // The name of the field which triggers the hide/show. Must be in the same set of children.
										'value' => 'image', // The value which determines if this field should be shown
									),
								)
							),

							// YouTube Video ID
							'youtube_video_id'   => new Fieldmanager_Textfield(
								array(
									'label'       => 'YouTube Video ID',
									'attributes'  => array( 'style' => 'width:100%' ),
									'description' => 'Enter only the YouTube ID, e.g. "EVBl9-kvKHA"',
									'display_if'  => array( // This works on most, but not all field types
										'src'   => 'hero_conditional', // The name of the field which triggers the hide/show. Must be in the same set of children.
										'value' => 'yt', // The value which determines if this field should be shown
									),
								)
							),

							// Facebook Video URL
							'facebook_video_url' => new Fieldmanager_Textfield(
								array(
									'label'       => 'Facebook Video URL',
									'attributes'  => array( 'style' => 'width:100%' ),
									'description' => 'Enter full URL to facebook video, e.g. "https://www.facebook.com/atscaleevents/videos/1741691622770601"',
									'display_if'  => array( // This works on most, but not all field types
										'src'   => 'hero_conditional', // The name of the field which triggers the hide/show. Must be in the same set of children.
										'value' => 'fb', // The value which determines if this field should be shown
									),
								)
							),

							// Vimeo Video ID
							'vimeo_video_id'     => new Fieldmanager_Textfield(
								array(
									'label'       => 'Vimeo Video ID',
									'attributes'  => array( 'style' => 'width:100%' ),
									'description' => 'Enter only the Vimeo ID, e.g. "265401201"',
									'display_if'  => array( // This works on most, but not all field types
										'src'   => 'hero_conditional', // The name of the field which triggers the hide/show. Must be in the same set of children.
										'value' => 'vm', // The value which determines if this field should be shown
									),
								)
							),

							// Hero Caption
							'hero_caption'       => new Fieldmanager_TextArea(
								false, array(
									'label'       => 'Hero Caption',
									'attributes'  => array( 'style' => 'width:100%' ),
									'description' => 'Hero Caption',
								)
							),
						),
					)
				);
				$fm->add_meta_box( 'Hero Fields', 'post' );

				// Author's Name
				$fm = new Fieldmanager_Textfield(
					array(
						'name'       => 'author',
						'attributes' => array( 'style' => 'width:100%' ),
					)
				);
				$fm->add_meta_box( 'Author\'s Name', 'post' );

				// Display date option
				$fm = new Fieldmanager_Checkbox(
					'Show Date', array(
						'name'            => 'show_date',
						'default_value'   => 'true',
						'checked_value'   => 'true',
						'unchecked_value' => 'false',
					)
				);
				$fm->add_meta_box( 'Date', 'post' );

				// Intro copy
				$fm = new Fieldmanager_RichTextArea(
					false,
					array(
						'name'            => 'intro_copy',
						'attributes'      => array( 'style' => 'width:100%' ),
						'editor_settings' => array(
							'media_buttons' => false,
						),
					)
				);
				$fm->add_meta_box( 'Intro Copy', 'post' );

				// Related Links
				$fm = new Fieldmanager_Group(
					array(
						'name'           => 'reading_list',
						'limit'          => 3,
						'add_more_label' => 'Add another Link',
						'sortable'       => true,
						'collapsible'    => true,
						'collapsed'      => true,
						'label'          => 'Link',
						'children'       => array(

							'title' => new Fieldmanager_TextField(
								false,
								array(
									'label'       => 'Title',
									'attributes'  => array( 'style' => 'width:100%' ),
									'description' => 'Title',
								)
							),
							'link'  => new Fieldmanager_Link(
								false,
								array(
									'label'       => 'Link',
									'attributes'  => array( 'style' => 'width:100%' ),
									'description' => 'Full URL',
								)
							),
						),
					)
				);
				$fm->add_meta_box( 'Recommended Reading Links', 'post' );

				// Content Block Repeater
				$fm = new Fieldmanager_Group(
					array(
						'name'           => 'content_blocks',
						'limit'          => 0,
						'add_more_label' => 'Add another content block',
						'sortable'       => true,
						'collapsible'    => true,
						'collapsed'      => true,
						'label'          => 'Content Block',
						'children'       => array(

							// Content Type Select
							'content_type_select' => new Fieldmanager_Select(
								'Content Block Type',
								array(
									'label'   => 'Content Type',
									'options' => array(
										'text'  => 'Text',
										'image' => 'Image',
										'fb'    => 'Facebook Video',
										'yt'    => 'YouTube Video',
										'vm'    => 'Vimeo Video',
									),
								)
							),

							// Text Block and Pull Quote
							'text'                => new Fieldmanager_Group(
								array(
									'label'      => 'Text Content Block',
									'tabbed'     => 'vertical',
									'display_if' => array(
										'src'   => 'content_type_select',
										'value' => 'text',
									),
									'children'   => array(

										'body'             => new Fieldmanager_RichTextArea(
											'Body',
											array(
												'label' => 'Body',
												'attributes' => array( 'style' => 'width:100%' ),
												'editor_settings' => array(
													'media_buttons' => false,
												),
											)
										),

										'pull_quote_group' => new Fieldmanager_Group(
											array(
												'limit'    => 1,
												'label'    => 'Pull Quote',
												'children' => array(

													// Pull Quote
													'pull_quote'       => new Fieldmanager_TextField(
														array(
															'label' => 'Pull Quote Text',
															'attributes' => array( 'style' => 'width:100%' ),
														)
													),

													// Pull Quote Author
													'pull_quote_author' => new Fieldmanager_TextField(
														array(
															'label' => 'Pull Quote Author',
															'attributes' => array( 'style' => 'width:100%' ),
														)
													),

												),
											)
										),
									),
								)
							),

							// Image Block and Caption
							'image'               => new Fieldmanager_Group(
								array(
									'label'      => 'Image Content Block',
									'display_if' => array(
										'src'   => 'content_type_select',
										'value' => 'image',
									),
									'children'   => array(
										'images' => new Fieldmanager_Group(
											array(
												'tabbed'   => true,
												'limit'    => 20,
												'add_more_label' => 'Add another Image',
												'sortable' => true,
												'collapsible' => true,
												'collapsed' => true,
												'children' => array(
													'image-hi' => new Fieldmanager_Media( 'Image (Desktop)' ),
													'image-lo' => new Fieldmanager_Media( 'Image (Mobile)' ),
													'caption'          => new Fieldmanager_TextArea(
														array(
															'label' => 'Caption',
															'attributes' => array( 'style' => 'width:100%' ),
														)
													),
												),
											)
										),
									),
								)
							),

							// YouTube Video Block and Caption
							'youtube'             => new Fieldmanager_Group(
								array(
									'label'      => '"YouTube" Content',
									'display_if' => array(
										'src'   => 'content_type_select',
										'value' => 'yt',
									),
									'children'   => array(
										'videos' => new Fieldmanager_Group(
											array(
												'limit'    => 10,
												'add_more_label' => 'Add another Video',
												'sortable' => true,
												'collapsible' => true,
												'collapsed' => true,
												'children' => array(
													'youtube_video_id'    => new Fieldmanager_Textfield(
														array(
															'label'       => 'YouTube Video ID',
															'attributes'  => array( 'style' => 'width:100%' ),
															'description' => 'Enter only the YouTube ID, e.g. "EVBl9-kvKHA"',
															'display_if'  => array( // This works on most, but not all field types
																'src'   => 'content_type_select', // The name of the field which triggers the hide/show. Must be in the same set of children.
																'value' => 'yt', // The value which determines if this field should be shown
															),
														)
													),
													'caption'          => new Fieldmanager_TextArea(
														array(
															'label' => 'Caption',
															'attributes' => array( 'style' => 'width:100%' ),
														)
													),
												),
											)
										),
									),
								)
							),

							// Facebook Video Block and Caption
							'facebook'            => new Fieldmanager_Group(
								array(
									'label'      => '"Facebook Video" Content',
									'display_if' => array(
										'src'   => 'content_type_select',
										'value' => 'fb',
									),
									'children'   => array(
										'videos' => new Fieldmanager_Group(
											array(
												'limit'    => 10,
												'add_more_label' => 'Add another Video',
												'sortable' => true,
												'collapsible' => true,
												'collapsed' => true,
												'children' => array(
													'facebook_video_url'  => new Fieldmanager_Textfield(
														array(
															'label'       => 'Facebook Video URL',
															'attributes'  => array( 'style' => 'width:100%' ),
															'description' => 'Enter full URL to facebook video, e.g. "https://www.facebook.com/atscaleevents/videos/1741691622770601"',
															'display_if'  => array( // This works on most, but not all field types
																'src'   => 'content_type_select', // The name of the field which triggers the hide/show. Must be in the same set of children.
																'value' => 'fb', // The value which determines if this field should be shown
															),
														)
													),
													'caption'          => new Fieldmanager_TextArea(
														array(
															'label' => 'Caption',
															'attributes' => array( 'style' => 'width:100%' ),
														)
													),
												),
											)
										),
									),
								)
							),

							// Vimeo Video Block and Caption
							'vimeo'               => new Fieldmanager_Group(
								array(
									'label'      => '"Vimeo" Content',
									'display_if' => array(
										'src'   => 'content_type_select',
										'value' => 'vm',
									),
									'children'   => array(
										'videos' => new Fieldmanager_Group(
											array(
												'limit'    => 10,
												'add_more_label' => 'Add another Video',
												'sortable' => true,
												'collapsible' => true,
												'collapsed' => true,
												'children' => array(
													'vimeo_video_id'    => new Fieldmanager_Textfield(
														array(
															'label'       => 'Vimeo Video ID',
															'attributes'  => array( 'style' => 'width:100%' ),
															'description' => 'Enter only the Vimeo ID, e.g. "265401201"',
															'display_if'  => array( // This works on most, but not all field types
																'src'   => 'content_type_select', // The name of the field which triggers the hide/show. Must be in the same set of children.
																'value' => 'vm', // The value which determines if this field should be shown
															),
														)
													),
													'caption'          => new Fieldmanager_TextArea(
														array(
															'label' => 'Caption',
															'attributes' => array( 'style' => 'width:100%' ),
														)
													),
												),
											)
										),
									),
								)
							),
						),
					)
				);
				$fm->add_meta_box( 'Content Block(s)', 'post' );
		}
	}

	DemoTech_Fields_Article::instance();`

**Comment by mstudio** [comment]
@iamseangrant, @spacedmonkey – I just learned of a fix for this via Blair at WordPress VIP and thought I'd share here. Per her note:

For FieldManager groups, there is a property `group_is_empty` that takes a callable. Here is a link to the documentation:

http://api.fieldmanager.org/source-class-Fieldmanager_Group.html#88-92

This property can be added to the array of arguments for each group, and it will solve this issue.
The group_is_empty property can be added like this:

```
$fm = new Fieldmanager_Group(
array(
    'name'           => 'content_blocks_group',
    'limit'          => 0,
    'add_more_label' => 'Add another content block',
    'sortable'       => true,
    'collapsible'    => true,
    'collapsed'      => false,
    'label'          => 'Content Block',
    'label_macro'    => array( 'Content Block: %s', 'content_type_select' ),
    'group_is_empty' => function( $values ) { return empty( $values['content_type_select'] ); },
    'children'       => array(
        // Content Type Select
        'content_type_select' => new Fieldmanager_Select(
            'Content Block Type',
            array(
                'label'   => 'Lead In Type',
                'options' => array(
                    'text_only'        => 'Text Only',
                    'text_image_bleed' => 'Text with Full Bleed Image',
                    'text_media_stack' => 'Text with Stacked Media',
                    'stat'             => 'Stat',
                    'pull_quote'       => 'Pull Quote',
                ),
            )
        ),
```
Using this pattern, you can add this property to any FieldManager groups that are exhibiting the unwanted behavior.
