### ISSUE TITLE
Autocomplete fields don't work in side context in Gutenberg

### ISSUE THREAD

**Issue by scottnelle** [alleyinteractive/wordpress-fieldmanager#710]
In the Gutenberg editor, autocomplete fields don't work when added to the `'side'` context. I suspect the reason may be to do with the way that the autocomplete events are attached to elements when the DOM is ready. Something about the `'side'` fields tucked in the "Extended Settings" drawer in the current Gutenberg experience seems to prevent this from happening.

# What should happen
Typing in an autocomplete field in the side context should fire an event to query the datasource with the string data that has been entered.

# What happens
When typing in an autocomplete field, no event seems to fire and no query is attempted.

**Comment by kevinfodness** [comment]
Fixed via #757
