### ISSUE TITLE
Submit to packagist?

### ISSUE THREAD

**Issue by jenkoian** [alleyinteractive/wordpress-fieldmanager#722]
As this plugin isn't in the official wordpress plugin directory it doesn't get mirrored on [wpackagist](https://wpackagist.org/), which is fair enough. However, any chance of submitting to regular [packagist](https://packagist.org/) for ease of install with composer?

**Comment by dlh01** [comment]
@kasparsd has also made this request in #728.

**Comment by johnbillion** [comment]
I'd also like to see this please, so we can get rid of the Fieldmanager submodule and pull it in via Composer instead.

**Comment by danielbachhuber** [comment]
@dlh01 Any chance we can make this happen? Shouldn't take more than a couple of clicks.

**Comment by danielbachhuber** [comment]
This is now live: https://packagist.org/packages/alleyinteractive/wordpress-fieldmanager

**Comment by dlh01** [comment]
Thanks @danielbachhuber!
