### ISSUE TITLE
Date displays wrong if date is before 1970s

### ISSUE THREAD

**Issue by ravatparmar** [alleyinteractive/wordpress-fieldmanager#723]
FieldManager-Datepicker shows the wrong date if the date is before 1970, 

The issue is when we have a before the 1970s date at that time timestamp will have a negative value and the Fieldmanager_Datepicker convert the negative value to the positive value so it displays the wrong date.

cc: @danielbachhuber

**Comment by ravatparmar** [comment]
PR: https://github.com/alleyinteractive/wordpress-fieldmanager/pull/724

**Comment by danielbachhuber** [comment]
@ravatparmar Can you provide a test case too?

**Comment by ravatparmar** [comment]
@danielbachhuber Added one test case, and please let me know if we need more test cases or I missed anything.

**Comment by danielbachhuber** [comment]
👍 Thanks @ravatparmar

**Comment by dlh01** [comment]
Fixed in #724.
