### ISSUE TITLE
Autocomplete with value from a value => label data source

### ISSUE THREAD

**Issue by bizmate** [alleyinteractive/wordpress-fieldmanager#727]
I will try to explain what I mean with the title above.
Fieldmanager_Autocomplete is great for quickly turning a field into an auto complete search but it is just based on the use a list of values returned and then when clicking on the item it then does populate the filed with this value but lets assume I am searching for a post attribute using 

```
self::POST_FIELD => new Fieldmanager_Autocomplete( __( 'code' ), [
	'name' => 'code',
	'show_edit_link' => true,
	'datasource' => new Fieldmanager_Datasource_Post( [
		'query_callback' => __NAMESPACE__ . '\\code_lookup',
	] )
]),
```
And then implement callback 
```
function code_lookup($fragment) {
	$query = new WC_Product_Query();
	$query->set( 'code', $fragment );
	$products = $query->get_products();

	$prods = [];
	/** @var \WC_Product_Simple $product */
	foreach ($products as $product) {
		$prods[$product->get_id()] = 'code: ' . $product->get_code() . ' (' . $product->get_name() . ')';
	}

	return $prods;
}
```

So i get a list of products i can yes select like
| code: 123 (My first product) |
| code: 234 (My first product) |
|......|

At this point when i click on the first result the field is populated with value "123"

**Comment by mboynes** [comment]
Hi @bizmate, it sounds like what you probably want to do is create your own data source by extending `Fieldmanager_Datasource`. Use the existing extensions (post, term, user) as reference. The existing extensions are not meant to solve every use case (nor is Fieldmanager itself) — they are meant to cover the majority of cases and the Fieldmanager architecture is meant to be extendable enough for developers to cover the rest with relative ease.

I hope this helps!

**Comment by bizmate** [comment]
Hi @mboynes thanks for the reply. I am already achieving the implementation of the custom data source using the query_callback, this is not the problem above. It is more how to return this custom DTO back to the Autocomplete so that it can set the value instead of a label as i outlined above.

**Comment by mboynes** [comment]
I don't think you're following my suggestion. Instead of the approach you took above, you should create a new class which extends `Fieldmanager_Datasource`, and in the `get_items()` method you should do what you're doing in your `code_lookup()` function. Again, if you need any guidance on how to extend `Fieldmanager_Datasource`, the three existing extensions serve as good examples.

Best of luck!
