### ISSUE TITLE
Add to Composer Packagist

### ISSUE THREAD

**Issue by kasparsd** [alleyinteractive/wordpress-fieldmanager#728]
To allow installing the plugin via `composer require alleyinteractive/wordpress-fieldmanager` we need to [register the GitHub repository at Packagist](https://packagist.org/packages/submit).

It appears that there are no packages at the `alleyinteractive` namespace yet so it would be nice to claim it, too.

**Comment by dlh01** [comment]
Duplicate of #722. Please keep an eye on that ticket for any activity on this front!
