### ISSUE TITLE
Exposing fields in the WordPress JSON API?

### ISSUE THREAD

**Issue by matt-bernhardt** [alleyinteractive/wordpress-fieldmanager#739]
I'm starting to experiment with FieldManager, and noticed that the fields don't seem to - by default - be included in WordPress' API?

I'm using the code samples on FieldManager.org, with a current (5.0.3 at the moment) version of WordPress. I see the fields on the edit screen for posts, and notice the values persisting from save to re-edit  - so I'm pretty sure they're being stored in the database correctly. Yet when I look at the same post in the WP API, I don't see these fields.

I also see a PR from a year+ ago #583 - which is still open.

Am I correct in interpreting all of this to mean that fields defined by FieldManager are not yet exposed via the API? Or is there something that I'm missing?

**Comment by dlh01** [comment]
Hey @matt-bernhardt — you're correct that data saved by Fieldmanager as meta isn't automatically exposed in the REST API. Along with the PR you referenced, this issue is being tracked in #404.
