### ISSUE TITLE
Can $default_value be dependent on a selected field value?

### ISSUE THREAD

**Issue by kujain** [alleyinteractive/wordpress-fieldmanager#751]
Currently$default_value is static. I am trying to find a way to make it dependent on a selected value in a dropdown, so it doesn't need to be static. Is it possible to do so?
eg. I have a fieldname: `eb_module_type`.  Can default value call a function that returns a string based on the value of the above selected fieldname ? `self::get_module_property($eb_module_type)['title']`

Thanks!

**Comment by mboynes** [comment]
Hey @kujain, you may have already drawn this conclusion but you can absolutely call a function that returns a dynamic value for this or any other property!
