### ISSUE TITLE
Update button stays active in Gutenberg for any post which has Fieldmanger field

### ISSUE THREAD

**Issue by sayedtaqui** [alleyinteractive/wordpress-fieldmanager#758]
When any post/page or custom post types have a Fieldmanger field used, the update button stays active even when there are no changes made to the post.

Tested with 
- Fieldmanger v1.2.4 ( latest )
- [Fieldmanger Demo plugin](https://github.com/alleyinteractive/fieldmanager-demos) v0.1 
- WordPress v5.2.4
- Default Twenty Nineteen Theme v1.4
- With and without Gutenberg plugin v6.7.0
( with no other plugins active )

![2019-10-25 12 29 51](https://user-images.githubusercontent.com/6297436/67550447-24cfeb00-f724-11e9-9d5a-2638f7c63ffe.gif)

**Comment by srtfisher** [comment]
This looks like an issue with Gutenberg/Core and not with Fieldmanager. Here's an example video replicating this issue: https://www.loom.com/share/75d60edc67bd4fa88d1180bc2f4cfe3d

1. Update button always active with Fieldmanager enabled.
2. Update button always active with Fieldmanager disabled (but another plugin causing a meta box to appear).
3. Update button works properly with no meta boxes and Fieldmanager disabled.

Seems like core will always have the update button clickable if a meta box is included in the post.
