### ISSUE TITLE
Posts Are Not Reciprocal

### ISSUE THREAD

**Issue by ian-pvd** [alleyinteractive/wordpress-fieldmanager#760]
My Custom Posts Types are not reciprocal.

While attempting to create many-to-many relationships between custom post types, it is not clear from [the documentation](http://api.fieldmanager.org/class-Fieldmanager_Datasource_Post.html#$reciprocal) how to configure this behavior. I am attempting to link custom post types together using the `name` value of the corresponding FM config for the `reciprocal` property on `Fieldmanager_Datasource_Post`.

For example: 
- Field name: https://github.com/ian-pvd/fieldmanager-tests/commit/931fbf59e02a3e43137163eb3dcc2d300f96ff1b#diff-78210b0bbb170b63ae72b5caa5330ff6R16
- Reciprocal value: https://github.com/ian-pvd/fieldmanager-tests/commit/931fbf59e02a3e43137163eb3dcc2d300f96ff1b#diff-0f48eaf096dede145577d7b2d85328d5R24

My goal is to create reciprocal links between two custom post types (for example: Hikes & Mountains) so that selecting a linked Mountain using the FM metabox on a Hike will cause the linked data to be updated in metadata for the linked Mountain in a way that WP and Fieldmanager can use it on the front end and in metaboxes.

**Steps To Reproduce:**

1. Install and activate the `alleyinteractive/wordpress-fieldmanager` and `alleyinteractive/meta-inspector` plugins.
2. Create two custom post types. (See: [https://github.com/ian-pvd/fieldmanager-tests/commit/7e727a7fe7275b006a4fc4d89d2a88794a1b4a9b](https://github.com/ian-pvd/fieldmanager-tests/commit/7e727a7fe7275b006a4fc4d89d2a88794a1b4a9b))
3. Add a reciprocal fieldmanager config. (See: [https://github.com/ian-pvd/fieldmanager-tests/commit/931fbf59e02a3e43137163eb3dcc2d300f96ff1b](https://github.com/ian-pvd/fieldmanager-tests/commit/931fbf59e02a3e43137163eb3dcc2d300f96ff1b))
4. Add posts to the custom post types. For example:

        Mountains: Wittenberg, Cornell, Slide Mountain
        Hikes: Slide Mountain Loop, Burroughs Range Trail

5. Link CPT posts together using the FM meta boxes. For example:

        Burroughs Range Trail: Slide, Cornell, Wittenberg
        
        Slide Mountain: Slide Mountain Loop

**Expected Results:**

- Linked post meta should be stored in a single `mountain_linked_hikes` or `hike_linked_mountains` key, so that it can be easily retrieved for display on the front end of the site.
- Posts which are linked to a CPT using the FM metabox on that CPT's edit screen should show up in the FM metabox on the edit screen for the other CPT which they are linked to.

**Actual Results:**

- Linked post meta is stored in multiple keys. There will be as many keys as there are associations set in _other_ posts. However nothing will populate the array value unless it is added to this post.
![Screen Shot 2019-11-09 at 19 10 44](https://user-images.githubusercontent.com/1553012/68536750-ddea1400-0325-11ea-9467-809ef5079eaa.png)
- Mountains linked to a Hike with the FM metabox on the Hike edit page are not listed in the FM metabox on the Mountain edit page.
![Screen Shot 2019-11-09 at 19 13 04](https://user-images.githubusercontent.com/1553012/68536754-e4788b80-0325-11ea-86b1-40ca70e7fdb0.png)
*Linked Hikes on the "Slide Mountain" edit page. Includes "Slide Mountain Trail"*
![Screen Shot 2019-11-09 at 19 13 12](https://user-images.githubusercontent.com/1553012/68536753-e4788b80-0325-11ea-98e6-666914ed84a0.png)
*Linked Mountains on the "Slide Mountain Trail" edit page. Does not include "Slide Mountain"*

**More Info:**

Plugin Version: 1.2.4

WordPress Version: 5.2.2

**Comment by mboynes** [comment]
Hey @ian-pvd, sorry for taking so long to get back to you. Seems like a cool site/plugin you were building, I hope it made it live!

You may have already figured this out, but in order for this to work how you're expecting, the fields need to [store their data unserialized using `'serialize_data' => false`](https://fieldmanager.org/docs/misc/storing-data-unserialized/), so each iteration of the repeating field is storing the referencing id within its own meta key. Since reciprocal relationships may happen from multiple sources, it's not possible to store that data in a serialized array (well, possible perhaps, but not in a bug-free way 😉 ). Here's the update you'd need to make:

```diff
/**
 * Hike Mountains CPT fields config.
 *
 * Adds a metabox for associating Hikes with the Mountains CPT.
 */
function fmtests_fm_group_hike_mountains() {
	$fm = new Fieldmanager_Autocomplete(
		[
			'name'               => 'hike_linked_mountains',
			'label'              => __( 'Mountains summited on this hike.', 'fieldmanager-tests' ),
			'limit'              => 0,
			'sortable'           => true,
			'one_label_per_item' => false,
			'field_class'        => 'autocomplete',
+			'serialize_data'     => false,
			'datasource'         => new Fieldmanager_Datasource_Post(
				[
					'reciprocal' => 'mountain_linked_hikes',
					'query_args' => [ 'post_type' => 'mountains' ],
				]
			),
		]
	);

	$fm->add_meta_box(
		__( 'Hike Mountains', 'fieldmanager-tests' ),
		[ 'hikes' ],
		'side',
		'default'
	);
}
---
/**
 * Mountain Hikes CPT fields config.
 *
 * Adds a metabox for associating Mountains with the Hikes CPT.
 */
function fmtests_fm_group_mountain_hikes() {
	$fm = new Fieldmanager_Autocomplete(
		[
			'name'               => 'mountain_linked_hikes',
			'label'              => __( 'Hikes which summit this mountain.', 'fieldmanager-tests' ),
			'limit'              => 0,
			'one_label_per_item' => false,
			'field_class'        => 'autocomplete',
+			'serialize_data'     => false,
			'datasource'         => new Fieldmanager_Datasource_Post(
				[
					'reciprocal' => 'hike_linked_mountains',
					'query_args' => [ 'post_type' => 'hikes' ],
				]
			),
		]
	);

	$fm->add_meta_box(
		__( 'Mountain Hikes', 'fieldmanager-tests' ),
		[ 'mountains' ],
		'side',
		'default'
	);
}
```

You're right to point out that the docs don't detail this well. I'll add a tutorial on fieldmanager.org on how to do this, and try to make the docs clearer in some way. Thanks for the suggestion!
