### ISSUE TITLE
Gutenburg and Fieldmanager

### ISSUE THREAD

**Issue by jjrdev** [alleyinteractive/wordpress-fieldmanager#762]
I know not really an issue, but trying to get some definitive solution for adding fieldmanager to pages using gutenburg.  right now i have

```
function show_edit_form_after_title() {
    global $post, $wp_meta_boxes;
    do_meta_boxes( get_current_screen(), 'show_after_title', $post );
    unset( $wp_meta_boxes['post']['show_after_title'] );
}
add_action( 'edit_form_after_title', 'show_edit_form_after_title' );
```
and
```
add_action( 'fm_post_page', 'fmModules');
function fmModules()
{
	$fm = new Fieldmanager_Group(array(
		'name' => 'fmModules',
		'label' => __( 'Modules', 'mysite' ),
		'collapsed' => false,
		'children' => get_module_module_component()
	));
	$fm->add_meta_box(__( 'Page Modules', 'mysite' ), 'page', 'show_after_title', 'high');
}
```
I realise edit_form_after_title isnt available in gutenburg, just wondering if there is a like for like solution? i guess this is the clue. https://developer.wordpress.org/block-editor/developers/backward-compatibility/meta-box/

but is there a guide specifically for field manager? I'd be grateful for any recommendations

**Comment by jameswburke** [comment]
Hey @jjrdev, this is a great ask, unfortunately we don't have a good solution for you. I'd suggest keeping an eye on Gutenberg development. If this becomes feasible, we'll evaluate it at that time.
