### ISSUE TITLE
Can't uncheck all checkboxes if serialize_data set to false

### ISSUE THREAD

**Issue by mogmarsh** [alleyinteractive/wordpress-fieldmanager#764]
In a `Fieldmanager_Checkboxes` input, if `serialize_data` is set to `false`, you cannot uncheck all the checkboxes and update a previously saved value.

If you have some options checked, save it, then uncheck them all, it doesn't register that you want to uncheck them all, and stays at the last setting.

Here's a code example:

```php
add_action( 'fm_post_post', function() {
	( new Fieldmanager_Group( [
		'name'           => 'test',
		'serialize_data' => false,
		'children'       => [
			'checkboxes' => new Fieldmanager_Checkboxes(
				'Checkboxes',
				[ 'options' => [ 'One', 'Two', 'Three' ] ]
			),
		]
	] ) )->add_meta_box( 'Testing Serialize Data with Checkboxes', 'post' );
} );
```

**Comment by mslinnea** [comment]
This issue here is similar to https://github.com/alleyinteractive/wordpress-fieldmanager/issues/685 and expanding https://github.com/alleyinteractive/wordpress-fieldmanager/pull/686 to also include Fieldmanager_Checkboxes fixes the issue.
