### ISSUE TITLE
Add two fields to a metabox without additional wrapper

### ISSUE THREAD

**Issue by sarahmonster** [alleyinteractive/wordpress-fieldmanager#765]
I am trying to add two fields to a meta box, which is easily done using `Fieldmanager_Group`, but the output winds up looking quite awkward:

<img width="292" alt="Screenshot 2020-02-04 at 13 47 20" src="https://user-images.githubusercontent.com/376315/73839232-61c07900-480d-11ea-8c7a-b5e6edadd50a.png">

From a UI perspective, it would definitely make sense to skip showing the group wrapper if there's only one group or top-level element in that meta box.

Is there a way of accomplishing this in projects that use Fieldmanager?

Vaguely related: #334, #529

**Comment by dlh01** [comment]
Hey @sarahmonster,

It looks like `Link` is both the label of the group and the title of the meta box. Does removing the label from the group accomplish what you're after?

**Comment by sarahmonster** [comment]
You know, I didn't even think of doing that, but it absolutely does. Thank you so much!

I'd be happy to contribute to some documentation for future people-like-me if there's somewhere to contribute and it's be helpful, but otherwise this completely solves my personal problem, so I'll close the issue. Thanks again! 😄

**Comment by dlh01** [comment]
More docs are always helpful! Can you think of a where they might have been placed so that they would have been there at the right moment while you were working on these fields?
