### ISSUE TITLE
Getting PHP Warning when publishing or updating the post

### ISSUE THREAD

**Issue by speedyprem** [alleyinteractive/wordpress-fieldmanager#766]
Getting the PHP Warning when publishing or updating the post: argument supplied for foreach() warning (https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/util/class-fieldmanager-util-validation.php#L292)

**Comment by dlh01** [comment]
Hi @speedyprem! Can you please share a code sample that can be used to replicate the warning?
