### ISSUE TITLE
null value is possible when array is expected

### ISSUE THREAD

**Issue by banderon** [alleyinteractive/wordpress-fieldmanager#767]
The [render_field()](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/context/class-fieldmanager-context.php#L90) method in the `Fieldmanager_Context` class has the following code:
```php
$data = array_key_exists( 'data', $args ) ? $args['data'] : null;
...
$field = $this->fm->element_markup( $data );
```
This makes it possible for `$data` to be `null`. However, the [element_markup()](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/class-fieldmanager-field.php#L473) method that's called above (from the `Fieldmanager_Field` class) expects an array only.
```php
* @param array $values The current values of this element, in a tree structure
...
public function element_markup( $values = array() ) {
	$values = $this->preload_alter_values( $values );
```
Likewise, the [preload_alter_values()](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/class-fieldmanager-field.php#L735) method that's immediately called also expects and returns an array.
```php
 * @param  array $values The values to load.
 * @return array $values The loaded values.
 */
public function preload_alter_values( $values ) {
	return apply_filters( 'fm_preload_alter_values', $values, $this );
}
```

**Comment by dlh01** [comment]
Thanks for the report, @banderon!

We think that this is a shortfall in the documentation for `element_markup()`. In practice, it handles almost any data type, such as a scalar value with non-repeatable fields:

https://github.com/alleyinteractive/wordpress-fieldmanager/blob/861ba6d2d8301f36374231565a68a698136e4b0f/php/class-fieldmanager-field.php#L593

Fieldmanager also purposefully checks for `null` downstream from `element_markup()` as a signal to use the `default_value` property:

https://github.com/alleyinteractive/wordpress-fieldmanager/blob/861ba6d2d8301f36374231565a68a698136e4b0f/php/class-fieldmanager-field.php#L701-L703

I've opened #784 to try to standardize the documentation around the method in a way that makes it clear that broad a range of types is allowed. Feel free to comment there with any suggestions!
