### ISSUE TITLE
Adding titles 

### ISSUE THREAD

**Issue by Sitetools** [alleyinteractive/wordpress-fieldmanager#768]
Hi,
I'm using Fieldmanager_Group, is it possible to add headings between fields?
I use this section for Site wide / generic data but a long list of fields can be confusing for the user. Being able to group a few fields below a heading would be very useful.

Cheers

Robin

**Comment by jameswburke** [comment]
Hi @Sitetools, this is a great question. Internally we've had a `Fieldmanager_Content` class that's occasionally been used to render static content (plaintext, html, etc.), and could be utilized to add headings around in between other fields.

I've pushed #781 and will be working towards including it in our next release. Until then, feel free to implement the class directly on your project(s).

Usage would be something like,
```php
new Fieldmanager_Content(
  [
    'name'         => 'html_content',
    'content'      => '<h2>My Group Heading</h2>.',
    'content_type' => 'html'
  ]
)
```

**Comment by Sitetools** [comment]
Fantastic, thank you for that great reply.
