### ISSUE TITLE
Any tutorial or guide for understanding how to properly use this plugin

### ISSUE THREAD

**Issue by Hiteshs-addweb** [alleyinteractive/wordpress-fieldmanager#770]
Is there any specific tutorial or guide available that have instructions for user/developer. So that understanding can be made of how to properly use this plugin in the code environment of the site.

**Comment by mboynes** [comment]
Hi @Hiteshs-addweb, yes, you'll find documentation and other instructions at http://fieldmanager.org/ (more specifically, http://fieldmanager.org/docs/). Thanks for checking out the plugin, we hope you enjoy it!
