### ISSUE TITLE
Fieldmanager_Datepicker not working in WordPress 5.6 on Gutenberg Post

### ISSUE THREAD

**Issue by mslinnea** [alleyinteractive/wordpress-fieldmanager#793]
The Fieldmanager_Datepicker JS isn't working in WordPress 5.6 on the Gutenberg edit post screen, but it does work fine in WordPress 5.5.2.

It also works fine in WordPress 5.6 for the classic editor.

Code to reproduce the issue:

```
add_action( 'fm_post', function () {
    $fm_date = new Fieldmanager_Datepicker( 'Date' );
    $fm_date->add_meta_box( 'Date', 'post' );
} );
```

**Comment by mslinnea** [comment]
I tried using the enable jquery migrate plugin to load an earlier version of jquery, but that didn't resolve this issue.

**Comment by dlh01** [comment]
There are some issues in Gutenberg relating to changes in timing within `wp.domReady`. It seems to be firing earlier than it used to, before any of the datepickers are visible:

https://github.com/WordPress/gutenberg/issues/27607
https://github.com/WordPress/gutenberg/issues/25330

**Comment by mslinnea** [comment]
I think this same issue is preventing ajax autocomplete from working as well.

**Comment by jomurgel** [comment]
In the context of FieldManager, I'm not sure this is (or is completely) a `wp.domReady` timing issue. Looking at the elements that are being targeted to kick off the field js, when Gutenberg is enabled the query returns an undefined value unless fired after the dom is loaded.

**Comment by dlh01** [comment]
@mslinnea Are you able to test #796?

**Comment by mslinnea** [comment]
@dlh01 Yes I just tested #796 and that resolved this issue!  That patch solves both the datepicker and autocomplete issues.  I think that solution is good to merge.
