### ISSUE TITLE
Fieldmanager_Autocomplete field not getting enabled in Gutenberg

### ISSUE THREAD

**Issue by corywebb** [alleyinteractive/wordpress-fieldmanager#799]
We have a `Fieldmanager_Autocomplete` field getting loaded with Gutenberg, and the `enable_autocomplete` function is not seeing the field.

The script is looking for this selector: `$( 'input.fm-autocomplete:visible' )`, and it is not seeing the field because it does not yet match the `:visible` part of the selector. Also, the toggle event isn't getting triggered because the box that contains the autocomplete field doesn't have a matching selector:

```
$( document ).on( 'fm_collapsible_toggle fm_added_element fm_displayif_toggle fm_activate_tab', fm.autocomplete.enable_autocomplete );
```

If I edit the JS file and remove the `:visible` part of the selector, the field works properly.

**Comment by dlh01** [comment]
Hey @corywebb, and thanks for the report. A fix for this issue was merged just a few days ago, in #796. Could you check out `master` to see whether your autocomplete field works as expected?

**Comment by corywebb** [comment]
Thanks @dlh01! That looks like a good fix. I'll test it ASAP and let you know. I should have mentioned that I have tested with version 1.3.0.

**Comment by dlh01** [comment]
Hey @corywebb, any update on testing against the `master` branch?

**Comment by corywebb** [comment]
@dlh01 hey, yes, the master branch resolved the issue. Thanks for checking in.

**Comment by dlh01** [comment]
Thanks!
