### ISSUE TITLE
FM to ACF

### ISSUE THREAD

**Issue by anteksiler** [alleyinteractive/wordpress-fieldmanager#805]
Hi everyone,

With a new client, we need to move to ACF Pro as they need more functionality than what FM offers at the moment.

Have you guys ever faced this or share some pointers on how to face this?

As far as I can see, the only problem is with Groups to Repeater conversion.

Thanks in advance,

**Comment by dlh01** [comment]
Hey @anteksiler! I don't personally have any experience with such a migration, but we do have quite a bit of experience with bending Fieldmanager to meet the needs of our clients 😄 

What's the functionality in ACF that led to the decision to migrate? If we can't help make Fieldmanager do it now, we can at least file some issues for future enhancements.

**Comment by anteksiler** [comment]
@dlh01 Hi David, it is mostly about adding custom fields to taxonomies/categories. I did not find anything related to this inside the documentation.

**Comment by mboynes** [comment]
hey @anteksiler, fields can be added to taxonomies using the [Term Context](https://fieldmanager.org/docs/contexts/term-context/). This allows you to render fields on the new and/or edit term screen, read data from term meta, and save data to term meta. I hope this helps!
