### ISSUE TITLE
`save_term_fields()` does not check the term ID, can result in data corruption

### ISSUE THREAD

**Issue by johnbillion** [alleyinteractive/wordpress-fieldmanager#831]
The `save_fields_for_post()` method in the post context has a guard condition where it checks the post ID before saving data to it. This is for the situation where another post gets updated when a post is saved and prevents meta data being saved to another post. Ref: https://github.com/alleyinteractive/wordpress-fieldmanager/blob/6e46daf1a0e643f28802a7ca0c5466870a0530fb/php/context/class-fieldmanager-context-post.php#L185

This was introduced in #147.

There is no such protection for terms. If a term gets saved and some code updates another term, Fieldmanager will write its term meta to that term too. Ref: https://github.com/alleyinteractive/wordpress-fieldmanager/blob/6e46daf1a0e643f28802a7ca0c5466870a0530fb/php/context/class-fieldmanager-context-term.php#L284

**Comment by mboynes** [comment]
Thanks @johnbillion! Great find. We'll dig into it and try to ship a new release today.

**Comment by mboynes** [comment]
@johnbillion this ended up being a little more complicated than I anticipated! I have a PR open to address which I need to do more testing on. Would you also be able to give it a quick try?

Thanks!

**Comment by mboynes** [comment]
@johnbillion @alwaysblank I just shipped 1.5.0 which resolves this issue. Thanks again!
