### ISSUE TITLE
[RESOLVED] Get posts with meta query

### ISSUE THREAD

**Issue by carlos-widgilabs** [alleyinteractive/wordpress-fieldmanager#833]
It's not possible, more than 100 issues and none with a relationship between get_posts and meta_query!

I have this metafiled registered:

`$fm_date_end   = new Fieldmanager_Datepicker(
		array(
			'name'        => 'date_start',
			'label'       => 'Data de término',
			'use_time'    => true,
			'date_format' => 'Y-m-d',
			'js_opts'     => array(
				'dateFormat' => 'dd-mm-yy',
			),
		)
	);
`

`$fm_all = new Fieldmanager_Group(
		array(
			'name'     => 'event_date_all',
			'children' => array(
				'date_start' => $fm_date_start
			),
		)
	);
	$fm_all->add_meta_box( 'Data Evento', array( 'event' ) );`

How do I get the posts with this date_start meta box?

I have this code

`$args = array(
	'post_type' 	        => 'event',
	'posts_per_page' 	=> -1,
	'orderby'                 => 'meta_value',
	'order'                     => 'DESC',
	'meta_key'              => 'date_start',
	'meta_value'	       => date( "Ymd" )
	'meta_compare'     => '>',
	'suppress_filters'.   => true,
	'meta_query'		=> array(
		'meta_key' 		=>  'date_start',
		'meta_value'    	=>  $myFilterDate,
		'compare' 		=>  '=>',
	),
);

$posts_events = get_posts( $args );`

the $posts_events return empty. ps. exists events registered.

**Comment by carlos-widgilabs** [comment]
Solution: add attribute in Fieldmanager_Datepicker ( ...,  'index' => 'date_start', // Or any name you want. )

**Comment by mboynes** [comment]
Hey @carlos-widgilabs, looks like you found one of the solutions, great! There is another which I'll mention for posterity, and that is to [store the group's data unserialized](https://fieldmanager.org/docs/misc/storing-data-unserialized/), which creates a separation between data and presentation.
