### ISSUE TITLE
Autocomplete validation doesn't work

### ISSUE THREAD

**Issue by darylldoyle** [alleyinteractive/wordpress-fieldmanager#842]
https://github.com/alleyinteractive/wordpress-fieldmanager/pull/748 was opened to fix this issue but it seems it never got merged.

https://github.com/alleyinteractive/wordpress-fieldmanager/pull/748/commits/3bb29849d90b75485400888c1d1171a46d25e814 is the specific change that needs making.

As there are no filters to change the ignore patterns, it's not something that we can patch within our own codebases.

**Comment by dlh01** [comment]
Thanks for flagging that PR, @darylldoyle! I wonder why the fix never ended up making it in.

Unless there are new complications with validation to consider, do you think you could add these details to #321? I'm thinking this ticket can be closed as a duplicate.
