### ISSUE TITLE
Hash Fieldmanager_Password values?

### ISSUE THREAD

**Issue by bjorn2404** [alleyinteractive/wordpress-fieldmanager#847]
Just noticing that Fieldmanager_Password values appear to be stored in the database as plain text by default, which seems like a large security concern. Is there a method available to hash the values or any plans to add this?

**Comment by mboynes** [comment]
Hi @bjorn2404, thanks for the questions. The short answers are: yes, there are methods available to hash the data in both WordPress and PHP e.g. `wp_hash_password`, and no there are no plans to bake something into `Fieldmanager_Password`. Of course, I agree with you in principle that password data shouldn't be stored as plain text in a database, and if that's how one is using `Fieldmanager_Password` I also hope that they choose to hash or encrypt that data. That would be an implementation detail outside of Fieldmanager's default purview.

Some clarifications for posterity. Fields in Fieldmanager don't care where, how, or even _if_ their data is stored. Fields care about safely rendering markup for an individual field, with escaped state data if provided. Contexts are in control of data storage and retrieval. While Fields do provide clues to contexts about how their data should be _sanitized_, it's up to the context to choose to adopt that or not.

`Fieldmanager_Password` doesn't represent a password per se, it merely represents a field of `<input type="password" />`. What happens to any submitted form data is up to the developer.

If you'd like to hash a password, when you instantiate the field, you can set the option `'sanitize'` and the data will pass through that callable when a context sanitizes the field (again, if the context so chooses, and all core contexts do this). That might look something like this:

```php
$field = new \Fieldmanager_Password( [
   'name' => 'field_name',
   'label' => 'Password',
   'sanitize'` => 'wp_hash_password',
] );
```

In this case, I used the WordPress core function `wp_hash_password`, which is a self-salting password hasher. It's extremely important to note that hashing a value this way is unidirectional, and that value cannot be retrieved later. For a password used to login, that's a good thing. For other data that might be problematic, and those values perhaps should be encrypted in such a way that they could later be decrypted. Again, this is up to the developer to decide what needs to happen based on their needs.

I hope this helps you with your feature development!

**Comment by bjorn2404** [comment]
Thanks for the info!
