### ISSUE TITLE
Modifying values before save

### ISSUE THREAD

**Issue by theMikeD** [alleyinteractive/wordpress-fieldmanager#855]
I have a config whereby the values of a select box on Tab A are taken from a repeater on Tab B. For example: a list of cities is created in Tab B via a repeater (fields for `city_code` and `city_nice_name`), and each of those cities is an element in the selectbox in Tab A.

This leads to pain when the following happens

1. User selects a city using the selects box
2. Without saving, user then switches to Tab B and changes the `city_code` (the select box key) for the city selected in step 1
3. User saves

Result:
1. the UX displays that no value is set in the selectbox, but the actual saved option still shows the old `city_code` value.

I went looking for a filter I could use to ensure that the selected item actually exists, and found [this](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/main/php/context/class-fieldmanager-context-page.php#L73), but the parent function is marked as deprecated and debugging confirms that it's not being called.

If there is another filter suitable to task, I can't find it; all other filters I see don't include the uniqid to tie it to a specific form.

Is there a way to achieve what I need to do here?

**Comment by mboynes** [comment]
Hi @theMikeD, yes, if I understand you correctly then the [`fm_presave_alter_values`](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/bce98e86391d76810dfd9bd892c5bf1b2f7096a1/php/class-fieldmanager-field.php#L1083-L1090) filter should be what you need. Let me know if that doesn't do the trick! 😄
