### ISSUE TITLE
Update class constructor docblocks to support specifying an `array` or a `string` for `$label`

### ISSUE THREAD

**Issue by nikkifurls** [alleyinteractive/wordpress-fieldmanager#867]
### Description of the bug

Each constructor has a `$label` parameter which can be a `string` or an `array`.

Currently, docblocks only specify that `$label` can be a string, making the docblock incorrect.

This causes issues with code quality tools like `phpstan`.

### Steps To Reproduce

1. Set up `phpstan` on a project with `wordpress-fieldmanager`
2. Register a new Fieldmanager field, specifying an `array` for `$label`, e.g.
```
new \Fieldmanager_Group(
	[
		'name'     => 'settings',
		'children' => [
			'api_key' => new \Fieldmanager_TextField( __( 'API Key', 'wp-plugin' ) ),
		],
	]
);
```
4. Run `phpstan`
5. Notice errors like `Parameter #1 $label of class Fieldmanager_Group constructor expects string, array<string, array<string, Fieldmanager_TextField>|string> given.`

**Comment by renatonascalves** [comment]
This is not a bug, since this doesn't break anything. It's more like an enhancement for phpstan.
