### ISSUE TITLE
Docs: Where is the list of valid `$attributes` and what they do?

### ISSUE THREAD

**Issue by theMikeD** [alleyinteractive/wordpress-fieldmanager#872]
### Description of the documentation inaccuracy

`https://api.fieldmanager.org/class-Fieldmanager_Field.html#$attributes`

This one line appears to be all available documentation related to attributes. I can find nothing describing which attributes are available for which field, and what they mean/control. Hopefully I'm wrong and it's just not obvious!

**Comment by mogmarsh** [comment]
@theMikeD it is just a pass through to the html. You can add any attribute supported by html spec, and it will add it to the form field. Fieldmanager doesn't do anything based on the attributes, so they don't control anything.

**Comment by mboynes** [comment]
+1 to what @mogmarsh said, and I'll add some additional detail.

First, that you can pass _any_ attributes, not just attributes supported by HTML spec (recognizing that you could be writing invalid markup, but the point is that Fieldmanager doesn't stop you from doing that).

Second, how/where the attributes get applied can be confusing, given the vast array of field types and the variety of markup required for each one. As a couple of for-instances to illustrate the point...

* for radio buttons or checkboxes, do the attributes get added to every input? do they get added to the input elements or the div wrapping the input and label? ([individual inputs](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/584979f3e59b2173fa71633a07c39c0050b11347/templates/options-radios.php#L20))
* for media, do the attributes get added to the hidden input, the button, or the div wrapping the preview or... what? ([the button](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/584979f3e59b2173fa71633a07c39c0050b11347/php/class-fieldmanager-media.php#L218))
* for datepickers with the time option, which input(s) do the attributes get added to? ([just the date input](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/584979f3e59b2173fa71633a07c39c0050b11347/templates/datepicker.php#L21), not the time fields)

If you [search the codebase for `get_element_attributes()`](https://github.com/search?q=repo%3Aalleyinteractive%2Fwordpress-fieldmanager%20get_element_attributes&type=code) you can easily track it down for each field type. We tried to be as consistent, deliberate, and intuitive about it as we could in applying these attributes over the years, but I'll be the first to admit that its application is ambiguous, which clearly suggests that we could have done better!

I'm going to close the issue for now, but if you have any followup feature requests @theMikeD, do share them here and I'll be happy to reopen it!

**Comment by theMikeD** [comment]
Thanks team!
